### ISSUE TITLE
ViewFinder position and size

### ISSUE THREAD

**Issue by sayus2884** [dm77/barcodescanner#101]
Hi, first off, I love this library and thanks a lot for making this.

Here's my question, is there any way to change the ViewFinder's size and position? I want to re-position the ViewFinder  above the screen and overlay a layout below it instead of placing it in a linear layout and put views below and use weights.

Thanks.

**Comment by dm77** [comment]
Thanks to @marchelo , his pull request has been now merged in. It might help with what you are looking for. Changes available in v1.8

**Comment by sayus2884** [comment]
Hi, sorry for the late reply. Unfortunately, I tried but failed. I haven't really handled canvases in Android nor Java much. Is there a method somewhere equivalent to setViewFinderLocation() or setViewFinderSize() or something?

**Comment by marchelo** [comment]
I thing now there is no such API to do that, but you may try next trick(starting from v1.8):

        mScannerView = new ZXingScannerView(this) {
            @Override
            protected IViewFinder createViewFinderView(Context context) {
                return new CustomViewFinderView(context);
            }
        };
        setContentView(mScannerView);

    ...
    private static class CustomViewFinderView extends ViewFinderView {
        ...
        @Override
        public synchronized void updateFramingRect() {
             super.updateFramingRect();                                               // init framing rect with default values
             super.getFramingRect().set(left, top, right, bottom);           // set your custom values to rect
        }
    }

But I think we should have a proper API for such thing.

**Comment by sayus2884** [comment]
thanks @marchelo, I'll try that out.
