### ISSUE TITLE
Custom Scan Fragment

### ISSUE THREAD

**Issue by rex3du** [dm77/barcodescanner#103]
Is there anyway to custom scan fragment layout? 

I wanna add a message view on the top the screen displaying scan result and some info in the App. 

Any suggestions? Thank you in advance !

**Comment by crebstock** [comment]
The sample shows how to do a scanner fragment, and it even implements dialogs for switching cameras, etc.  So you could use that as a base to implement a pop up.  It should only be a few lines to throw up a dialog in the handleResult method:

https://github.com/dm77/barcodescanner/blob/master/zxing/sample/src/main/java/me/dm7/barcodescanner/zxing/sample/ScannerFragment.java

https://github.com/dm77/barcodescanner/blob/master/zbar/sample/src/main/java/me/dm7/barcodescanner/zbar/sample/ScannerFragment.java

**Comment by rex3du** [comment]
@crebstock Thank you for your suggestion. However, the client request to show the result without dialog. I added overlay on the screen view. Below is my code to add overlay view. 
 @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment

        messageView = inflater.inflate(R.layout.message_scan_result, container, false);
        messageView.setVisibility(View.GONE);
        fullnameTextView = (TextView)messageView.findViewById(R.id.textView_fullname_scanmessage);
        regNumberTextView = (TextView)messageView.findViewById(R.id.textView_regNumber_scanmessage);
        ticketTypeTextIVew = (TextView)messageView.findViewById(R.id.textView_tickettype_scanmessage);
        statusImageView = (ImageView)messageView.findViewById(R.id.imageView_checkinStatus_scanmessage);

        closeButton = (ImageButton)messageView.findViewById(R.id.imagebutton_close_scanmessage);

        closeButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                messageView.setVisibility(View.GONE);
            }
        });
        
        mScannerView.addView(messageView);

        return mScannerView;
    }
