### ISSUE TITLE
Zbar stops my camera from working

### ISSUE THREAD

**Issue by csanonymus** [dm77/barcodescanner#104]
I started using Zbar in my project for a couple of days now and I have this weird problem that my camera literally stops working after a few minutes of testing. I used it for like 5 minutes and it started showing me a blank screen, no image from camera and then I tried using my phone's camera and it says `Camera not available`. No other app can enable my camera after this issue I can just restart my phone and than it gets back to normal. The library is great but this is kind of annoying and I'm scared for my users thinking that my app breaks their phones or something.. I haven't dived into the library's code yet but maybe someone else could find a fix or something.. My phone is a Sony Xperia T.

Thanks!

**Comment by dm77** [comment]
Seems like it is just an issue with sony xperia devices. Quite a few issues show up in a a quick google search. Also example video https://www.youtube.com/watch?v=MxDrpJU2fgs
