### ISSUE TITLE
Library fails to select best preview size when not in fullscreen

### ISSUE THREAD

**Issue by dmo60** [dm77/barcodescanner#105]
First of all: This is a nice library! Thank you so much! 

I'm currently trying to include the ScannerView in one of my projects and everything works fine, except the library does not seem to select the best matching aspect ration for the camera preview.

I don't want to show the ScannerView fullscreen, instead I want to embed it in my layout. The space available for the ScannerView roughly matches a 4:3 aspect ratio. There is a matching `Camera.Size` for 4:3 available, but still the ScannerView selects the 16:9 size.

I think I also found the reason for this miscalculation: Since 1c0c74f9e445a5dea0cdc87484c89be651dbdcdf, you adjust the surface size based on the view's dimensions, but you still try to calculate the best matching camera preview size based on the screen resolution.

`CameraPreview.java` line 192:
```
int w = screenResolution.x;
int h = screenResolution.y;
if (DisplayUtils.getScreenOrientation(getContext()) == Configuration.ORIENTATION_PORTRAIT) {
    w = screenResolution.y;
    h = screenResolution.x;
}
```

You probably have to use `getWidth()`/`getHeight()` instead of the screen resolution here as well.

Perhaps I'll find the time to create a Pull Request with the fix, but if you want to fix it yourself, go ahead!

**Comment by OzTK** [comment]
+1! I hope the PR will be merged soon! :)

**Comment by Guidgem** [comment]
+1! I'm also looking forward to this fix! I keep getting the black bars on each size of the screen if the view is not fullscreen. BTW, thanks for the awesome library! ;)

**Comment by dm77** [comment]
This weekend guys. Sorry for the delay. Thanks so much @dmo60

**Comment by dm77** [comment]
Merged, will release version 1.8.1 in next 24 to 48 hours.

**Comment by OzTK** [comment]
Thanks a lot! And thanks for this great library :)

**Comment by Guidgem** [comment]
Great news! Thanks again.

**Comment by mincel** [comment]
This is a great library! Thank you!

I am currently developing an application with a full screen ZXingScannerView. It has an overlay button bar to control flash and some other things at the bottom. After this merge unfortunately I am not able to make camera preview full screen. Am I missing something?

**Comment by dm77** [comment]
@mincel sorry about that. Will update to 1.8.2 shortly.

**Comment by mincel** [comment]
Great! Thanks a lot!

**Comment by xanscale** [comment]
hi @dm77 , i have square area for ZBarScannerView. with 1.8.2 i see black bar on sides. but i prefer to crop other sides. (like centerCrop)

there is a way to do something like that?

**Comment by xolan** [comment]
I would also like an option to fill parent width or height, and crop the other.
