### ISSUE TITLE
Hide laser for scanner UI and set the width and height of viewfinder (rectangular area)

### ISSUE THREAD

**Issue by pyee** [dm77/barcodescanner#107]
Noted that we can change colour for scanner UI, border, mask and laser. Is it possible for us to hide the laser for scanner? What is the mask referring to? Lastly, I used LinearLayout for displaying scanner above the remaining UI. but the rectangular area was squeezed. If not mistaken, it was shown by a ratio. How can I modify it? with my desired width and height?

**Comment by dm77** [comment]
You can provide your own ViewFinder in verison 1.8, thanks to this pull request #80 

Regarding the camera preview issue, you have two options:
1.) Use a full screen theme and overlay elements on top of the scanner UI
or 
2. ) Version 1.8.1 (will be released in next 48 hours) will include this pull request: #106
