### ISSUE TITLE
Q: ZBar vs ZXing

### ISSUE THREAD

**Issue by Crustus** [dm77/barcodescanner#108]
Hi,
can anyone exmplain me please, whats the difference between this two modules?
Thx a lot

**Comment by crebstock** [comment]
Personal preference.  

From my opinion and anecdotal experience:
 - ZXing is the more active library
 - ZBar scans faster
 - ZBar has had a few cases where it actually read the wrong barcode for me

**Comment by bruceFend** [comment]
zxing can return not only the result of barcode but also the coordinates of three position detection patterns, while zbar can't achieve this

**Comment by dm77** [comment]
also zbar SDK hasn't been updated in 3 years.
