### ISSUE TITLE
Add documentation for proguard configuration

### ISSUE THREAD

**Issue by Zlate87** [dm77/barcodescanner#109]
Hi

I was using the zbar library in an application that is obfuscated by proguard and had some problems when inflating the me.dm7.barcodescanner.zbar.ZBarScannerView view.

For me the following proguard configuration fixed the issue:

```
-keep class me.dm7.barcodescanner.** {
  *;
}

-keep class net.sourceforge.zbar.** {
  *;
}
```

It would be nice if this is documented.

**Comment by hastoukopsaro** [comment]
+1

**Comment by spirosoik** [comment]
@Zlate87 it worked for you this config?

**Comment by dm77** [comment]
Sorry for such a late reply. Thank you for the tip on proguard. I will add it to the README in next release.

**Comment by CMingTseng** [comment]
tip on proguard ? Where ?

Thx
