### ISSUE TITLE
Stop Transparency Before Scanner Appears

### ISSUE THREAD

**Issue by MobileMon** [dm77/barcodescanner#110]
I present the scanner in a dialogFragment. There is a split second delay before camera is active. The view is doing something though to make all views behind it transparent (and it even shows through my dialog to the content underneath it!)

Is there any way to stop this transparency until the camera officially loads?

**Comment by pw92** [comment]
@MobileMon How did you resolve this issue? Please leave some feedback for people like me who are facing this same issue.

**Comment by MobileMon** [comment]
@pw92 I had to do some hacks with the styling of the dialog

In values -> styles.xml put:

```
    <style name="Dialog" parent="Theme.AppCompat.Light.Dialog">
        <item name="android:buttonStyle">@style/BlackText.Button</item>
        <item name="buttonStyle">@style/BlackText.Button</item>
        <item name="android:windowIsFloating">true</item>
        <item name="android:backgroundDimAmount">0.00</item>
        <item name="android:windowBackground">@drawable/shadow_frame_dialog</item>
    </style>
```

in values-v21 -> styles.xml put:

```
<style name="Dialog" parent="Theme.AppCompat.Light.Dialog">
        <item name="android:buttonStyle">@style/BlackText.Button</item>
        <item name="buttonStyle">@style/BlackText.Button</item>
        <item name="android:windowIsFloating">true</item>
        <item name="android:backgroundDimAmount">0.00</item>
        <item name="android:actionMenuTextColor">@color/ipt_pure_white</item>
    </style>
```


Then the xml for android:windowBackground is 

```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item>
        <shape android:shape="rectangle"> <!-- this shape is used as shadow -->
            <padding android:bottom="5dp"
                android:left="5dp"
                android:right="5dp"
                android:top="5dp"/>
            <solid android:color="#44000000"/>
            <corners android:radius="5dp"/>
        </shape>
    </item>
</layer-list>

```
Basically on versions under 21 I had to take away the native dialog shadow and draw my own

I also do this to my DialogFragment but I'm not sure if its necessary, haven't had time to test:
`dialog.setStyle(DialogFragment.STYLE_NORMAL, R.style.Dialog);`
