### ISSUE TITLE
Cannot resolve symbol 'ZXingScannerView'

### ISSUE THREAD

**Issue by davidbilly** [dm77/barcodescanner#113]
Hi @dm77 ,

Thanks for the great library, but i faced this issue : Cannot resolve symbol 'ZXingScannerView'

Android Studio 
dependencies {
    compile 'me.dm7.barcodescanner:zxing:1.8.1'
    compile 'me.dm7.barcodescanner:zbar:1.8.1'
}

Screenshoot : 
<img width="809" alt="screen shot 2015-08-03 at 12 08 24 pm" src="https://cloud.githubusercontent.com/assets/3938103/9030688/7a2c7ab8-39d8-11e5-9f7c-83e50aa19172.png">

any idea on this?

**Comment by davidbilly** [comment]
@dm77 Sorry, it solved. I rebuild the whole project, sorry for newbie on Android Studio

**Comment by shriduttkothari** [comment]
same error with me... i hate Android Studio...I rebuild the whole project and problem got resolved, sorry for newbie on Android Studio
