### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by lduparc** [dm77/barcodescanner#117]
Using Zbar, sometimes the camera is not started and a black screen appear.

I have to close the application in order to be able to scan again. Even if I go back to the previous fragment and open my scanner fragment again it's not working.

Have any idea about this issue ?

Thanks

**Comment by sridhar87** [comment]
First, thanks for this wonderful library!

Even I am having the same issue with ZXing as well. I am able to scan 2-3 times continuously and then black screen appears.

I have mScannerView.startCamera() in handleResult() function

Any idea how this could be avoided and have the Scanner continuously scan barcodes?

**Comment by dm77** [comment]
Latest version 1.9 should fix this
