### ISSUE TITLE
The Scanner View is exactly at the mobile width on 1.8.1

### ISSUE THREAD

**Issue by yodutouf** [dm77/barcodescanner#118]
I was using the 1.7.1 version of your library. 
I switch today to the 1.8.1 version.
I notice that the screen width of the scanner view is smaller than the screen width of my phone on portrait mode.
You could find attache a capture of the view in 1.7.1 and 1.8.1.
My mobile is a Samsung Galaxy Nexus.

![version1-8-1](https://cloud.githubusercontent.com/assets/5493780/9577498/8bcca10c-4fe1-11e5-8385-1924267f96a6.png)
![version-1-7-1](https://cloud.githubusercontent.com/assets/5493780/9577504/9ea1d5ae-4fe1-11e5-988c-e05c43399070.png)

**Comment by dm77** [comment]
Please see #67
