### ISSUE TITLE
ZBar binaries for "all" architecture targets?

### ISSUE THREAD

**Issue by h32** [dm77/barcodescanner#119]
Hello, Is there any possibility to get binaries for all platforms (not only armv7 or x86 but mips and other also)?

**Comment by act262** [comment]
you can get all platforms arch `*.so` file,just use `APP_ABI := all` in `Application.mk`,and compile it,you will get those dir :`arm64-v8a` `armeabi`  `armeabi-v7a`  `mips`  `mips64` `x86`  `x86_64`

**Comment by dm77** [comment]
All the platform libraries are now available. See https://github.com/dm77/barcodescanner/tree/master/zbar/zbar/src/main/jniLibs
