### ISSUE TITLE
Camera Preview is Blank and Get Number of Cameras is not working on Android 5.0

### ISSUE THREAD

**Issue by vivekkiran** [dm77/barcodescanner#120]
Camera Preview is Blank and Get Number of Cameras is not working on Android 5.0 and above

**Comment by caleb-allen** [comment]
Had the issue as well, the issue was I had to request the camera permission from within the app.

**Comment by dm77** [comment]
Permissions issue like @caleb-allen  mentioned above. Please take a look at the zxing-sample to see how to handle camera permissions
