### ISSUE TITLE
preview area in landscape not getting full screen

### ISSUE THREAD

**Issue by falkontre** [dm77/barcodescanner#121]
Hi,

Surely, this is not an issue, but a lack of documentation....

If I rotate the device in landscape mode, the preview area will not expand to full screen, but preserves the ratio of the portrait mode.

How can I adjust (or config) it?

![2015-09-09 23 38 17](https://cloud.githubusercontent.com/assets/10171792/9776816/cf7391f4-575c-11e5-857a-2d716b661992.jpg)

**Comment by abuttlemur** [comment]
Have you made any findings on how to fix this?

**Comment by Rking788** [comment]
+1

**Comment by falkontre** [comment]
I moved towards another software (zxing)

**Comment by dm77** [comment]
Please see my comment in #8 . Please try solution provided in #67
