### ISSUE TITLE
Bug with Zbar

### ISSUE THREAD

**Issue by larsdecker** [dm77/barcodescanner#123]
Anyone else have this problem with the newest version of zbar ?

```
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/de.xxx.xxx-2/lib/arm/libiconv.so: has text relocations
```

**Comment by localhostEU** [comment]
Getting this error on Android 6 DP 3. I think it's related to [this](https://developer.android.com/preview/behavior-changes.html#behavior-runtime) change.

**Comment by larsdecker** [comment]
Yes, i have installed the Android 6 DP 3.  How i can fix that problem?

**Comment by localhostEU** [comment]
Yes, find zbar sources, fix text relocation, recompile and use new .so file.

**Comment by DevilGeek** [comment]
This is a real issues please someone fix it !

**Comment by shiSHARK** [comment]
Do you have any progress?

**Comment by dm77** [comment]
Sorry everyone will take a look at this this weekend

**Comment by dm77** [comment]
Similar to what @localhostEU mentioned, according to Fitz Gibbon from Google Developer Relations, the issue is:

>There was a recent change in Android M that causes shared libraries built with text relocations to fail to >load. (See docs here.) App developers that are using barcodescanner (specifically, the zbar sub->module) cannot target API level 23 because the .so's included in barcodescanner get caught by this >change. This is reported as issue #123.

>The fix is to rebuild these libraries with "position independent code", e.g., the cflag -fPIC.

**Comment by larsdecker** [comment]
Thanks a lot for your answer. Can anyone recompile the source
of zbar with the right flags?

**Comment by dm77** [comment]
I rebuilt the zbar libraries with fPIC flag like Fitz mentioned. Here is my commit (00d479213f52644c9bd3e0b7d8813c16ebda7add)

Can somebody please help me test the ZBar Sample APK file (https://www.dropbox.com/s/v2kmjhwt16na8mq/zbar_sample.apk?dl=0) on Android 6?  

If it works correctly, then I will release v1.8.3 with my fixes.

**Comment by dm77** [comment]
@larsdecker Thanks for your patience. Please let me know if you can test the sample APK file.

**Comment by larsdecker** [comment]
@dm77 The camera is not working with that version. I have a black screen with overlay of the zbar-scanner on a nexus 5 with android 6 dp 3.

**Comment by dm77** [comment]
Ah bummer. But you didn't see the error either? "java.lang.UnsatisfiedLinkError: dlopen failed". 

I tested the app on Android 2.3 (HTC Thunderbolt), Galaxy Nexus (4.2.2) and Nexus 5 (5.1.1) and it worked fine.

I wonder if its due to the permissions system in Android 6.

**Comment by larsdecker** [comment]
Works fine. The app didn´t get automatically the camera permission. When i manuell set the permission in the app settings, it works fine.

**Comment by dm77** [comment]
Awesome. Thank so much for testing @larsdecker. I will merge my changes into master and release 1.8.3. I will update the samples in future to request user for permission instead of showing black screen.

**Comment by larsdecker** [comment]
No Problem. Thanks a lot for your great lib.

**Comment by dm77** [comment]
Thanks @larsdecker . V1.8.3 has been released to maven central.

**Comment by amodkanthe** [comment]
Hi after this update build size got increased by almost 3 to 4 mb is there any way to reduce the build size while using zbar it is almost taking 6 mb now

**Comment by AlexTrotsenko** [comment]
Hello @dm77 . Thank you for fixing this issue. 

I was trying to find `"fixed"` sources of the [ZBar](https://github.com/ZBar/ZBar) as I am using it directly for QR scanning. But, looks like, there is nothing there yet.

Do you have your own fork of the `ZBar` repo with fixed `text relocations` issue or ?

**Comment by Zapnologica** [comment]
@dm77  Thank you so much for fixing and updating the library. There is nothing worse than doing an android update and your app doesn't work.

**Comment by ravneet2994** [comment]
Not working on android version 6.Please provide me a full code.

**Comment by SolveSoul** [comment]
Thanks for rebuilding the jniLibs, that made it an easy fix for me

**Comment by dwall9** [comment]
I have this problem with zbar .During scanning sometime its mismatch the barcode sometime swap the string of barcode and sometime trim the barcode length from starting and ending .but this issue occur only continuous scanning  2 out of 50 approx. anyone can help me?

**Comment by h0jeZvgoxFepBQ2C** [comment]
This issue is happening again for us on Android 6.0 with ```me.dm7.barcodescanner:zbar:1.9.13```

```
    java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/at.skill3d.flave.android-1/lib/arm/libiconv.so: has text relocations
        at java.lang.Runtime.loadLibrary(Runtime.java:372)
        at java.lang.System.loadLibrary(System.java:1076)
```

**Comment by h0jeZvgoxFepBQ2C** [comment]
I fixed it for us with this solution: https://github.com/dm77/barcodescanner/issues/170#issuecomment-289812814

**Comment by stoplus** [comment]
To reduce assembly size do this:
android {
    ......
    defaultConfig {
        ......
		......
		......
        ndk {
            abiFilters "armeabi-v7a"  // Specify an architecture that will be compatible with ndk (so other dependencies like mips, x86, armeabi, arm-v8, etc. will be filtered out)
        }
    }
}
