### ISSUE TITLE
is it possible to customize the layout

### ISSUE THREAD

**Issue by carlosnavas91** [dm77/barcodescanner#124]
I want to inflate with a custom layout, but how can I erase the existing preview camera layout

**Comment by SudarAbisheck** [comment]
This library might be useful for you. https://github.com/SudarAbisheck/ZXing-Orient

**Comment by jjhesk** [comment]
+1

**Comment by dm77** [comment]
This is possible now in 1.9. You can provide your layout. See samples

**Comment by JelleBlaauw** [comment]
Please link to this example. I'm using zbar.
