### ISSUE TITLE
Switch to Camera2 api instead of deprecated Camera

### ISSUE THREAD

**Issue by OzTK** [dm77/barcodescanner#125]
I'm not sure about the impact on other issues, but it might solve some problems, even if it is a major development

**Comment by pdebonte** [comment]
Camera2 requires Android 5, and according to Android Studio, that currently limits usage to <10% "of the devices that are active on the Google Play Store."

On the other hand, a few months ago, that was <1%, so it is growing.

**Comment by OzTK** [comment]
Thanks for the insights! I didn't know indeed that Camera2 was only available on 21+. Android Studio just mark it as so probably because I target 23. It would still be possible to conditionally use one or the other, but I'm not sure it would be worth it considering how the code would look like... 
Thanks for the app link I will check some devices I work on.

**Comment by RanganathanSamraj92** [comment]
zbar not working with api 23 android 6
