### ISSUE TITLE
Screen blinks black on first ZXingScannerView appearance.

### ISSUE THREAD

**Issue by Lingviston** [dm77/barcodescanner#128]
The issue is in header. I read somewhere why it is happening and know that it can be fixed by adding invisible SurfaceView to the same activity (so the necessary initialization done on Activity creation and invisible for user) but maybe there is better solution?

**Comment by revg75** [comment]
Anyone find a solution for this issue?  I am having same issue (only on some devices), but the flicker of the screen is really undesirable. If anyone knows how to avoid this please let the rest of us know :)

**Comment by milon87** [comment]
answer given by @revg75 is awesome. the main idea is ...
There is a less messy approach, just put getWindow().setFormat(PixelFormat.TRANSLUCENT); in the host activity's onCreate() callback before calling setContentView().
