### ISSUE TITLE
ArrayIndexOutOfBounds on 1.8.2

### ISSUE THREAD

**Issue by davisre** [dm77/barcodescanner#129]
When we upgraded zxing from 1.6.3 to 1.8.2, we started to see this exception on relatively new phones like the HTC Desire 626s and HTC One M9, both running Android 5.1:

```
java.lang.ArrayIndexOutOfBoundsException: length=783360; index=784079
       at me.dm7.barcodescanner.zxing.ZXingScannerView.onPreviewFrame(ZXingScannerView.java:97)
       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1573)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:155)
       at android.app.ActivityThread.main(ActivityThread.java:5725)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1030)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:825)
```

**Comment by dm77** [comment]
Thanks for submitting bug report. I will try to tackle this over the weekend.

**Comment by StupidHod** [comment]
I have get the issue, but I find the reason.

I used this view in a fragment. When the fragment is attached to a page view, it is resumed. However, I switch to another fragment just after the attach code, and the scanner page view is hidden, then in the "onPreviewFrame" function, it will get a wrong resolution.

**Comment by geek3** [comment]
I suspect the rotation is not considering the image data format

In my case these are my different debug values while inside onPreviewFrame
width x height = 720 x 720 (518400)
data.length = 777600
camera.getParameters().getPreviewFormat() = 17 (NV21)
ImageFormat.getBitsPerPixel(17) = 12
777600 * 8 / 12 = 518400

On another phone
width x height = 640 x 480 (307200)
data.length = 460800
camera.getParameters().getPreviewFormat() = 17 (NV21)
ImageFormat.getBitsPerPixel(17) = 12
460800 * 8 / 12 = 307200

I just saw this answer to rotate NV21 that I will try out by overriding onPreviewFrame.
http://stackoverflow.com/a/31425229

**Comment by tbruyelle** [comment]
For me the issue occurred just after a screen rotation.

**Comment by wtvic** [comment]
Any update for this issue?

**Comment by semieye** [comment]
Hi, I got this issue too, anybody fix it?

**Comment by NicoSordoni** [comment]
Hi to everybody.
I temporarily put the following patch. 
Is a shame, I know, but while waiting for the official fix, is the speedest solution I found.

public class HackyScannerView extends ZXingScannerView{
    public HackyScannerView(Context context) {
        super(context);
    }

    public HackyScannerView(Context context, AttributeSet attributeSet) {
        super(context, attributeSet);
    }

    @Override
    public void onPreviewFrame(byte[] data, Camera camera) {
        try {
            super.onPreviewFrame(data, camera);
        }catch (Exception e){}
    }
}
