### ISSUE TITLE
Active area of barcode scanner

### ISSUE THREAD

**Issue by YuckF** [dm77/barcodescanner#130]
Hi,
I would like to use your barcodescanner in my app but I couldn't find a way how to customize active area ( green box ). I would like to show only active area without camera preview background around it.
Is there any way to hide non-active area of scanner? 
The only solution which seems to me like possible is overriding LANDSCAPE_WIDTH_RATIO in ViewFinderView.class to 1 and then make whole scanner smaller, but I hope there is other way around.:-)
Thx for answers and sorry if this question is already answered somwhere but I couldn't find it.

**Comment by dm77** [comment]
Hi @YuckF very sorry for the delay. Will the pull request #80 help?

**Comment by dm77** [comment]
Fixed in #80
