### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by daisylassie** [dm77/barcodescanner#135]
hi dushyanth,

thx for sharing your barcodelibrary.

my questions are about performance:

a) is it nessasary to place the barcode in the rectangle or is this just for nice looking?
b) does the decoding only the rectangle or the whole screen?

if RECTANGLE, it would be faster if the rectangle isn't so high.
are there ideas to change this? or is it in zxing to change?

thx daisy

**Comment by dm77** [comment]
Hi @daisylassie 

To answer your questions:
a.) The viewfinder will force the user to maintain a certain distance from the qrcode. 
b.) Decoding happens only for the viewfinder area.

You can customize the view finder using info here #80
