### ISSUE TITLE
Barcodescanner scan random number

### ISSUE THREAD

**Issue by YuckF** [dm77/barcodescanner#138]
I am using your library for scaning barcode 128 in my app. It works fine but sometimes it just scan at random time even when there is no barcode near camera.. It scans always 16digit number starting with 01... Any ideas what could it be ?

**Comment by XavierLOTJ** [comment]
I've also experienced this, but it's very sporadic and I cannot reproduce at will.

**Comment by dm77** [comment]
@YuckF sorry for delay. Are you using ZBar or ZXing? I have noticed this happen with ZBar library in the past and came to conclusion that it has something to do the ZBar Android sdk itself.

**Comment by j-m-a-n** [comment]
Can confirm and replicate this behaviour using the ZBar SDK.. on a rather small EAN-13 barcode on a Nexus 5 device - happens everytime with the same barcode - seems fine using other devices though.

**Comment by dm77** [comment]
Yeah it is something the ZBar authors have to fix. But seems like they have ceased development on the Android version.
