### ISSUE TITLE
Barcodescanner scans different format and number

### ISSUE THREAD

**Issue by pmbfish40** [dm77/barcodescanner#140]
Scanning in Zxing sometimes I have different format and number. It happens when I am not moving my camera away from barcode it scans multiples time and then I got different result. What's the problem here?

**Comment by KostyaBakay** [comment]
I have the same issue too. For example sometimes camera scans the keyboard. How you solved this problem?

**Comment by dm77** [comment]
Unfortunately not in the scope of this project. Something to be resolve at the zxing library level
