### ISSUE TITLE
Open the camera is a little bit slow

### ISSUE THREAD

**Issue by UsherBaby** [dm77/barcodescanner#141]
Hope to improve the speed

**Comment by chx632996066** [comment]
+1

**Comment by chx632996066** [comment]
when I finish other Activity to back to ScanAcitivity, it need to wait > 3 seconds

**Comment by Rking788** [comment]
are you using the latest version? i just upgraded to 1.8.3 and it is much quicker than it used to be.

**Comment by dm77** [comment]
Thank you for your comment. Closing this issue in favor of #1
