### ISSUE TITLE
The Demo is not full screen 

### ISSUE THREAD

**Issue by xzwzyf0503** [dm77/barcodescanner#149]
Hi，
The demo running in my moblie phone is not full screen，it have black lines right and left。can i do same thing to solve？

![img](https://cloud.githubusercontent.com/assets/13127693/11891452/a5b310ca-a599-11e5-8dbb-19c2901dd8cd.png)

**Comment by onewilk** [comment]
@xzwzyf0503 change your style in style.xml and check your layout padding or margin...

**Comment by xzwzyf0503** [comment]
@onewilk Thank you for your answers! I didn't modify dm77's demo project And i checked and found that dm77 add a Cramer preView  to RelativeLayout Straightly,without padding or margin. It try to set Match_Parent to LayoutParams, but it didn't work. It seems that  carmer preView can't fill the full screen.

**Comment by dm77** [comment]
Marking it as duplicate
