### ISSUE TITLE
Hide Laser from ViewFinder

### ISSUE THREAD

**Issue by arsalananwar** [dm77/barcodescanner#151]
i want to hide or disable laser from view finder.

**Comment by jjhesk** [comment]
+1

**Comment by DanielMartinus** [comment]
+1

**Comment by johan-schoeman** [comment]
Change your code in class ViewFinderView as follows (i.e make the laser transparent):

    public void drawLaser(Canvas canvas) {
        // Draw a red "laser scanner" line through the middle to show decoding is active
        //mLaserPaint.setAlpha(SCANNER_ALPHA[scannerAlpha]);
	mLaserPaint.setAlpha(0);

**Comment by ervinmartirosyan** [comment]
`@Override
   public void drawLaser(Canvas canvas) {
      //no laser line
   }`

**Comment by dm77** [comment]
Enough solutions above. Additionally
1.) You can override this resource <color name="viewfinder_laser">#ffcc0000</color>
2.) Can also use the functionality added by #80
