### ISSUE TITLE
Cannot resolve method resumeCameraPreview

### ISSUE THREAD

**Issue by EnduroXPro** [dm77/barcodescanner#152]
I have copied your Activity "SimpleScannerActivity" and got the following compiling issue:

![screenshot](https://cloud.githubusercontent.com/assets/7962126/12058882/7b5ad3b4-af51-11e5-9525-f6b1f94f5ae6.png)

How can I solve this one?

**Comment by dm77** [comment]
That method was added as part of v1.8.4. Please make sure are using this version and that you have resync the gradle file in Android Studio.
