### ISSUE TITLE
startCamera and stopCamera not handling lifecycle properly

### ISSUE THREAD

**Issue by papageorgiouk** [dm77/barcodescanner#153]
I have startCamera onResume, and stopCamera onPause. But it won't detect barcodes, or not even start the camera preview if I pause the activity and come back to it.

Also, toggling the flash breaks barcode detection.

**Comment by thelittlefireman** [comment]
Same things evenif i put an stopCamera(); on the onDestroy() method

**Comment by vbuberen** [comment]
@papageorgiouk 
Yeah, the problem exists. You should call setResultHandler(context) again on your scannerView every time you call startCamera(). I use such method for handling camera in lifecycle control methods:
```
private void startCameraAndSetResultHandler() {
        if (scannerView != null) {
            scannerView.setResultHandler(this);
            scannerView.startCamera();
        }
```
And call this method in onCreate() and onResume().

**Comment by vbuberen** [comment]
@papageorgiouk 
Yeah, it is a problem.
I fixed this by calling resumeCameraPreview(this) on my scanner view in onResume() method.

**Comment by maxgunner** [comment]
The camera doesn't start and all i can see is a black screen.

**Comment by mradzinski** [comment]
Devices please? I can assure it's working perfectly fine on my Galaxy S4, Nexus 5 and Nexus 6.

**Comment by francescopedronomnys** [comment]
Had same problem on an S3 (running Android 4.3).

Fixed calling all the right lifecycle callbacks on ZXingScannerView instance.

` @Override
    protected void onStart() {
        super.onStart();
        mydecoderview.setResultHandler(this); // Register ourselves as a handler for scan results.
        mydecoderview.startCamera();
    }

    @Override
    protected void onResume() {
        super.onResume();
        mydecoderview.resumeCameraPreview(this);
    }

    @Override
    protected void onStop() {
        super.onStop();
        mydecoderview.stopCameraPreview();
        mydecoderview.stopCamera();
    }`

**Comment by selimeski** [comment]
Same problem and this was my solution. 

    @Override
    public void onStart() {
        super.onStart();
        mScannerView.setResultHandler(this); // Register ourselves as a handler for scan results.
        mScannerView.startCamera();
    }

    @Override
    public void onResume() {
        super.onResume();
        mScannerView.resumeCameraPreview(this);
    }

    @Override
    public void onStop() {
        super.onStop();
        mScannerView.stopCameraPreview();
        mScannerView.stopCamera();
    }

**Comment by todorBG** [comment]
@selimeski solution worked perfectly for me!

**Comment by CoolMind** [comment]
@selimeski, this was the solution of @francescopedronomnys. :D
And it has some bugs. For instance, if you use `setTorch()` method for a flash on/off, it won't call.
