### ISSUE TITLE
How to expand the camera in a small FrameLayout.

### ISSUE THREAD

**Issue by HectorFGarcia** [dm77/barcodescanner#157]
I'm using the scanner in a small FrameLayout inside a RelativeLayout, just like that:

![screen](https://cloud.githubusercontent.com/assets/12731574/12452034/b6f44e46-bf8c-11e5-90ed-5442ee7743dd.png)

But as you can see, now the camera has somekind of black margins both sides, I don't why or how to fix it.

The XML is quite simple

```
   <FrameLayout
    android:layout_width="match_parent"
    android:layout_height="170dp"
    android:layout_alignParentBottom="true">

    <FrameLayout
        android:id="@+id/scan_frame"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

   </FrameLayout>
```

How can I fix this?

**Comment by metow** [comment]
I too have the same problem here, may be rotating the camera to landscape mode would work, but I didnt succeed it doing it either. I'd be too glad if someone helps

**Comment by pavanjaju** [comment]
I am also having the same issue. Is there any way which we can scale the camera preview.?
