### ISSUE TITLE
Camera preview is black

### ISSUE THREAD

**Issue by devmaheshrb458** [dm77/barcodescanner#159]
I am writing an application to scan QR code. Where I am having two activities first one call second and in second one I am using the me.dm7.barcodescanner.zxing.ZXingScannerView to scan the QR code.
1. First time when I go to second activity for scanning it is working fine
2. When I go back by pressing the device back button and again going to second button the Camera preview is black.

Currently I am using the following setting :
zXingScannerView.setResultHandler(this);
zXingScannerView.setKeepScreenOn(true);
zXingScannerView.setFlash(flash);
zXingScannerView.setAutoFocus(autoFocus);
zXingScannerView.setFormats(ZXingScannerView.ALL_FORMATS);
zXingScannerView.setFormats((List) zXingScannerView.getFormats());
zXingScannerView.setWillNotDraw(true);

Need your suggestion on urgent basis.

**Comment by gowthamkumar7** [comment]
Yeah it seems there's a bug. 

But there's a work around if you are using fragment deattach and attach the fragment.

**Comment by abolfazlkalamati** [comment]
no , this is not a Bug
you must get Runtime Permission for Camera !
