### ISSUE TITLE
Camera scale

### ISSUE THREAD

**Issue by scarings** [dm77/barcodescanner#160]
i have a issue with scale camera when i put the content_frame inside linear layout:
the problem camera size not fit x and y.
here my code :
`
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal">
        <FrameLayout
            android:id="@+id/content_frame"
            android:layout_width="match_parent"
            android:layout_height="250dp"
            />
    </LinearLayout>
    <LinearLayout
        android:id="@+id/viewB"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_weight="0.4"
        android:orientation="horizontal"/>
`
how to scale camera auto fit x and y  ?

**Comment by faogustavo** [comment]
Did you solved this? need it too

**Comment by dm77** [comment]
Should have been solved by #219
