### ISSUE TITLE
How to move Red laser up-down 

### ISSUE THREAD

**Issue by akash09766** [dm77/barcodescanner#166]
is there any option with which we can move the red laser in up-down direction

**Comment by vbuberen** [comment]
@akash09766
No, it hasn`t such default methods or parameters which will allow you to move the red laser. This layout with the laser is taken directly from zxing library. 
The only option to make it move is to define behaviour of the red laser manually in source code.

**Comment by johan-schoeman** [comment]
Replace method drawLaser in class ViewFinderView with something like this

	private int cntr = 0;
	private boolean goingup = false; 
    public void drawLaser(Canvas canvas) {
        // Draw a red "laser scanner" line through the middle to show decoding is active
        mLaserPaint.setAlpha(SCANNER_ALPHA[scannerAlpha]);
        scannerAlpha = (scannerAlpha + 1) % SCANNER_ALPHA.length;
        int middle = mFramingRect.height() / 2 + mFramingRect.top;
		middle = middle + cntr;
		if ((cntr < 60) && (goingup == false)) {
           canvas.drawRect(mFramingRect.left + 2, middle - 1, mFramingRect.right - 1, middle + 2, mLaserPaint);
		   cntr = cntr + 4;
        } 
		
		if ((cntr >= 60) && (goingup == false)) goingup = true;
		
		if ((cntr > -60) && (goingup == true)) {
           canvas.drawRect(mFramingRect.left + 2, middle - 1, mFramingRect.right - 1, middle + 2, mLaserPaint);
		   cntr = cntr - 4;
        } 	

		if ((cntr <= -60) && (goingup == true)) goingup = false;		
		
        postInvalidateDelayed(ANIMATION_DELAY,
                mFramingRect.left - POINT_SIZE,
                mFramingRect.top - POINT_SIZE,
                mFramingRect.right + POINT_SIZE,
                mFramingRect.bottom + POINT_SIZE);			
    }

**Comment by akash09766** [comment]
@johan-schoeman  its working , thanks for the code

**Comment by johan-schoeman** [comment]
You need to edit the Java code. Do the changes in ViewfinderView.java, and recompile the code

**Comment by koderbober** [comment]
@johan-schoeman Ok, but how or where can I get ViewfinderView.java, if project contains .class files?
![class](https://cloud.githubusercontent.com/assets/7825231/15670475/597fbfa2-272e-11e6-8646-1faf4e292eec.png)

**Comment by koderbober** [comment]
If I try add library as modul, I get it: https://stackoverflow.com/questions/35866304/could-not-find-property-supportlibrarydependency

**Comment by johan-schoeman** [comment]
Here
https://github.com/dm77/barcodescanner/tree/master/core/src/main/java/me/dm7/barcodescanner/core

**Comment by johan-schoeman** [comment]
You need to start here 
https://github.com/dm77/barcodescanner

There is a core folder and a zbar folder. Together they will form one project. Inside the zbar folder is a libs folder that that contains zbar.jar. It is part of the project and needs to be in you project else the code will not compile

**Comment by ChauKhacHai** [comment]
how do i import ZxingScannerView to eclipse ?
// sorry my english :)

**Comment by prakashmp** [comment]
how to increase red laser top to bottom scan speed ??

**Comment by swarankargaurav1** [comment]
> Replace method drawLaser in class ViewFinderView with something like this
> 
> ```
> private int cntr = 0;
> private boolean goingup = false; 
> public void drawLaser(Canvas canvas) {
>     // Draw a red "laser scanner" line through the middle to show decoding is active
>     mLaserPaint.setAlpha(SCANNER_ALPHA[scannerAlpha]);
>     scannerAlpha = (scannerAlpha + 1) % SCANNER_ALPHA.length;
>     int middle = mFramingRect.height() / 2 + mFramingRect.top;
>     middle = middle + cntr;
>     if ((cntr < 60) && (goingup == false)) {
>        canvas.drawRect(mFramingRect.left + 2, middle - 1, mFramingRect.right - 1, middle + 2, mLaserPaint);
>        cntr = cntr + 4;
>     } 
> 
>     if ((cntr >= 60) && (goingup == false)) goingup = true;
> 
>     if ((cntr > -60) && (goingup == true)) {
>        canvas.drawRect(mFramingRect.left + 2, middle - 1, mFramingRect.right - 1, middle + 2, mLaserPaint);
>        cntr = cntr - 4;
>     }   
> 
>     if ((cntr <= -60) && (goingup == true)) goingup = false;        
> 
>     postInvalidateDelayed(ANIMATION_DELAY,
>             mFramingRect.left - POINT_SIZE,
>             mFramingRect.top - POINT_SIZE,
>             mFramingRect.right + POINT_SIZE,
>             mFramingRect.bottom + POINT_SIZE);          
> }   
> ```

this is not working. my lasser is not moving up and down
