### ISSUE TITLE
very slow frame rate in Amazon device and not scanning QR codes

### ISSUE THREAD

**Issue by dhawal-sheth** [dm77/barcodescanner#167]
After integtrating zxing into my app, it is working fine on regular Android devices.

On Amazon fire, the frame refresh is very slow and QR code scan is not working from my app. Sample app is working fine though.

**Comment by dm77** [comment]
Ah ok. If the sample app is working fine, then I would say this is something you will have to debug on your end. Sorry for not being much help. Good luck
