### ISSUE TITLE
Preview front camera upside down

### ISSUE THREAD

**Issue by BackPackerDz** [dm77/barcodescanner#172]
Hi, please can you help me, when I try the library in front camera, I have this result ! 

![device-2016-02-10-202207](https://cloud.githubusercontent.com/assets/8436726/12958887/1d466de8-d034-11e5-87e7-c5586d8da7f6.png)

**Comment by radsen** [comment]
Hi guys, do you have a suggestions or a fix for this. I'm facing the same problem

**Comment by jmuthad** [comment]
I'll have a pull request in on this in a bit but this only happens on devices where the front facing camera has a different orientation then the back facing camera because the library only checks the back facing camera for orientation.
