### ISSUE TITLE
Black screen on OS 6.0

### ISSUE THREAD

**Issue by maniacs-engineerica** [dm77/barcodescanner#177]
For devices with OS 6.0 the camera preview shows a black screen.

**Comment by carlosandresSanchez** [comment]
Help! I have the same problem!

**Comment by dieppe** [comment]
With Android M (6.0) a new permission system has been released (similar to iOS, where the app asks for the permission when needed). If you build for target=23, you need to ask for the permission before you can use the camera.

You can see an example of that (using cordova) here: https://github.com/jnuine/phonegap-plugin-barcodescanner/blob/master/src/android/BarcodeScanner.java#L115-L152

If you need a more generic way of doing that, check http://developer.android.com/training/permissions/requesting.html

**Comment by maniacs-engineerica** [comment]
Excellent, it was the problem. Thanks, I hadn't heard about runtime permissions in Android M.

**Comment by maniacs-engineerica** [comment]
Problem is solved. I close the issue.

**Comment by khoudy** [comment]
could you tell me where I should put the function "onRequestPermissionResult" and "callScan" ? and where I should call it , please ?

**Comment by maniacs-engineerica** [comment]
Before scan you have to request permissions:

1) ActivityCompat.requestPermissions(activity, new String[] /*camera permission*/, 0);

Then, receive user permission answer in your activity:

2) onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {

if (/*permission is granted*/){
     callScan();
}
}

**Comment by khoudy** [comment]
thank you very much :)
