### ISSUE TITLE
Add support for EAN2 and EAN5 please - Common on many products

### ISSUE THREAD

**Issue by ethanwa** [dm77/barcodescanner#179]
2-digit (EAN 2) and 5-digit (EAN 5) are known as supplemental barcodes. These are generally used for periodicals (to indicate the serial number), or books and weighted products like food (to indicate the selling price), respectively. It's also very common on Comic Books to tell the Variant, Printing, and Issue number. It's also found on small bottles of alcohol and other small products. Thank you.

**Comment by dm77** [comment]
Thank you for reporting this. All this library does is use the official zxing and zbar libraries. For example the current supported formats for zxing are https://github.com/zxing/zxing/blob/47459f4bd7ce6b883321a298df26eb5e279f4a32/core/src/main/java/com/google/zxing/BarcodeFormat.java
