### ISSUE TITLE
It's too damn fast!

### ISSUE THREAD

**Issue by hohl** [dm77/barcodescanner#181]
Great work! I tried a few various libraries but this one is definitely the best. However now since my app is almost finished I let it test by some users. And most of them complaint that the result view opens "before they finished scanning the barcode". In fact scanning works so damn fast, that you don't even recognize that they already scanned the barcode. (You don't even see it in the preview view, because before the barcode gets displayed, the `handleResult` method opens the next view.)

Is there any way to delay that? What I want is that the user must hold the scanner for 500ms or 1s at the barcode before it really detects it. My idea would be to "recolor" the crosshairs of the barcode preview once it's above the barcode and if it stays above the barcode for 500ms or so it will trigger the `handleResult`.

Did somebody already tried something like that? Or is there already some "delay" functionality implemented?

**Comment by OzTK** [comment]
I have the same problem. If you happen to be let's say in a supermarket (which applies to my case) where you can have many barcodes visible, it happens to be hard not to scan another barcode. On top of that, the problem I also have in my app is that the barcode is sometimes wrong. Like if it was not waiting for enough frames to be captured. Did you have that problem too with your test users?

**Comment by hohl** [comment]
My usage case is limited to POS system, so no I'm lucky that scanning the wrong barcode is unusual. But yes, my users told me that they where "unsure if they scanned the right barcode" mostly because there is no real feedback.

Would really love to see any solutions for this issue based on this library.

**Comment by ethanwa** [comment]
This is what I do. It puts a 2-second delay between scans:

`            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        Thread.sleep(2000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    runOnUiThread(new Runnable() {
                        @Override
                        public void run() {

                            // starts the scanning back up again
                            //mScannerView.startCamera();
                            mScannerView.resumeCameraPreview(SimpleScannerActivity.this);
                        }
                    });
                }
            }).start();`

**Comment by richin13** [comment]
Thanks @ethanwa, your solution prevents `handleResult` from being called twice (and even more times) when the user keeps the camera pointing to a code.

**Comment by yq2yizi** [comment]
I can not agree more!!  too fast i have ever seen
