### ISSUE TITLE
crash after do not grant the camera permission

### ISSUE THREAD

**Issue by liuqun567** [dm77/barcodescanner#186]
```
     android 5.1 
```

when system show the permission dialog and  click reject button, then crash.

java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                  at android.hardware.Camera.native_getParameters(Native Method)
                                  at android.hardware.Camera.getParameters(Camera.java:3195)
me.dm7.barcodescanner.core.CameraUtils.isFlashSupported(CameraUtils.java:32)
                         me.dm7.barcodescanner.core.BarcodeScannerView.setFlash(BarcodeScannerView.java:130)
                                  me.dm7.barcodescanner.core.BarcodeScannerView.setupCameraPreview(BarcodeScannerView.java:73)

**Comment by huahongyang** [comment]
i have a same problem work on android 5.1,if  in setting close the camera permission and open camera 
then crash
