### ISSUE TITLE
how to stop scan?

### ISSUE THREAD

**Issue by ouyangzn** [dm77/barcodescanner#194]
I want to stop scan, but still preview by camera, i can't find method to stop scan. Now i use             mScannerView.resumeCameraPreview(null);
to stop accept the result, but camera and zxing scanner is still work;

**Comment by CaiqueBrito** [comment]
Hi,

You tried to use stopCameraPreview(); ?

**Comment by micsha123** [comment]
Maybe you need to override `public void handleResult(Result result)` and put your logic into this method?
Or you want to stop before you get result? So it's better to use smth like fragments and FragmentManager - and attach and deattach when you need it.

**Comment by rgrewatz** [comment]
I'd also like to do something like this. mScannerView.resumeCameraPreview(null) is workable for me, but there's a short pause in the camera preview when the barcode is being parsed. 
It would be nice to be able to prevent this pause from happening by preventing the scanner from running and continuing the camera preview.

**Comment by maikkoko** [comment]
You can do something like mScannerView.setResultHandler(null). Do your logic and then set it back to the instance mScannerView.setResultHandler(this).

**Comment by rgrewatz** [comment]
I've tried this, but after calling setResultHandler(null), calling setResultHandler(this) does nothing. Need to call resumeCameraPreview(this) before it starts working again.
To clarify without going into code, my flow is simply: 
resumeCameraPreview(this) -> setResultHandler(this) -> setResultHandler(null) -> setResultHandler(this).

**Comment by CoolMind** [comment]
With `stopCameraPreview()` and maybe `stopCamera()`.
