### ISSUE TITLE
ZXing don't works with Facing Camera?

### ISSUE THREAD

**Issue by marcoslacerda** [dm77/barcodescanner#202]
Good Morning,

I'm trying to use the ZXing using the front camera unit (requirement requested by the client), but am not succeeding, since the front camera displays a mirror image.

I wonder if the ZXing possess support for this type of use, since there is startCamera method (int cameraID).

Thank you

**Comment by WingedToaster** [comment]
We are also experiencing this. Any tips?

**Comment by dm77** [comment]
Can you test with zxing-sample which lets you chose the camera? If you still have an issue please reopen.

**Comment by RahulRawat95** [comment]
I am having trouble when camera view is not full screen. When I use full screen camera view with match_parent as both height and width it works with front camera. But when I use it with match_parent width and 170dp height it stops working altogether.
