### ISSUE TITLE
Is it possible to change mode for layout?

### ISSUE THREAD

**Issue by micsha123** [dm77/barcodescanner#207]
Is it possible to make ScannerView always in landscape mode, even if phone is in portrait mode?

Thanks in advance.

**Comment by CaiqueBrito** [comment]
I had the same problem, the camera and scanner follow the screen orientation, if you really need to do that in landscape i suggest `override draw`, i did that, follow #80 to any question about it.

**Comment by micsha123** [comment]
CaiqueBrito, nice to meet you here, in my issue.
But the realy question is not about drawing scaner viewfinder, but also change mode of seeking barcodes. I can redraw viewfinder in vertical variant, but system will check only horizontal barcodes.
Am I right?

**Comment by CaiqueBrito** [comment]
micsha123, sadly yes... i think we can't customize the scanner to read in landscape mode when the activity is in portrait mode.
