### ISSUE TITLE
zbar: Reduce APK size

### ISSUE THREAD

**Issue by marioosh-net** [dm77/barcodescanner#212]
I'm using latest zbar (1.8.4) library. When build application i see it takes about 6mb. Using Zxing lib size of APK is noticable smaller. I see that zbar includes native libraries for: arm64-v8a, armeabi, armeabi-v7a, mips, mips64, x86, x86_64. Is a way to exclude some of them from APK? Is safe to include only armeabi ?

**Comment by punksta** [comment]
you can try this. 
```
release {
     ndk {
           abiFilters "armeabi-v7a", "armeabi"
     }
}
```

**Comment by marioosh-net** [comment]
Thank You. Is safe to include only armeabi ?

**Comment by punksta** [comment]
It is not good for release version, for example the last galaxy has x64 abi, but you can do it in debug build type. I compile debug for only my emulator abi

**Comment by dm77** [comment]
Thank you @punksta
