### ISSUE TITLE
White screen and camera frozen when rotating phone in portrait mode

### ISSUE THREAD

**Issue by OzTK** [dm77/barcodescanner#213]
Scenario:
1) Portrait mode is forced throughout the app
`setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);`
2) Rotate the phone (it stays in portrait mode)
3) Start the scanner activity

--> A white screen appears instead of the camera preview

**Comment by JsFlo** [comment]
I'm also forcing an orientation and saw this issue, fixed it by starting camera (startCamera()) and resuming the camera preview (resumeCameraPreview()) on onResume().

**Comment by FavoRiteKK** [comment]
In my case, I managed to fix it by adding configChanges="orientation|screenSize" in the AndroidManifest file.
