### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by AndrLin** [dm77/barcodescanner#221]
when I start activity , first see the activity view, and then black flash screen, and finally to see preview.
how can i solve the black flash screen？
Forgive my poor English！

**Comment by vfa-tuantt** [comment]
I have same issue. How can i fix this? Please let me know if you find solution. Thanks alot

**Comment by vfa-tuantt** [comment]
Hi @Mrmumu ,
I find solution for this issue:
Please add getWindow().setFormat(PixelFormat.TRANSLUCENT); into onCreate of your activity
It worked for me

**Comment by zongren** [comment]
@vfa-tuantt your solution works for me,thanks.

**Comment by Mrmumu** [comment]
@vfa-tuantt thanks

**Comment by sarpotdarsaurabh** [comment]
@vfa-tuantt thank u so much...I was having the screen blank flash then preview starting problem..your solution finally solved it. +1 man...
