### ISSUE TITLE
Init the ZBarScannerView from a Fragment

### ISSUE THREAD

**Issue by maikkoko** [dm77/barcodescanner#222]
Hi! Thank you for this amazing library. I have a question basically on usage basing on my implementation.

I put the scanner container inside a fragment which also houses 2 (fragment) children and viewed via viewpager.

_ParentFragment_:

```
@Override
public Fragment getItem(int position) {
    switch (position) {
        case PAGE_MANUAL:
            return ManualInputFragment.newInstance();
        case PAGE_SCAN:
            scanInputFragment = ScanInputFragment.newInstance();
                return scanInputFragment;
        default:
            return null;
    }
}
```

I also have a separate layout for the ScanInputFragment.

_fragment_scan_input.xml_

```
<?xml version="1.0" encoding="utf-8"?>

<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <FrameLayout
        android:id="@+id/content_frame"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

</FrameLayout>


```

_ScanInputFragment_

```
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.scan_input_fragment, container, false);


        ViewGroup contentFrame = (ViewGroup) view.findViewById(R.id.content_frame);
        mScannerView = new ZBarScannerView(getActivity());
        contentFrame.addView(mScannerView);

        return view;
    }
```

So my question is how can I inflate the fragment_scan_input.xml from parent fragment and then use ZBarScannerView. On my current implementation, no camera view is visible.

Thank you very much!

**Comment by maikkoko** [comment]
So I figured out the problem. The device I was testing is running on the new Android Marshmallow. The reason why the camera doesn't show a preview is the new runtime permission model of Android. 

Just do override requestPermissions on your activity when running on Marshmallow.

Cheers!

**Comment by milon87** [comment]
faced the same problem then I downgraded the target api lower than 23.

**Comment by Jenus** [comment]
support runtime permission, you need manually add the following at the onResume of your activity,
ActivityCompat.checkSelfPermission(BaseActivity.this, android.Manifest.permission.CAMERA)
                != PackageManager.PERMISSION_GRANTED)
