### ISSUE TITLE
When I start the ScannerActivity the screen would flash?

### ISSUE THREAD

**Issue by Dawnton** [dm77/barcodescanner#223]
Hello! Thank you for your library.But I find that when I start the scannerActivity the screen would flash first then the Activity would be launched.I don't know why.Can you repair the bug?

**Comment by yummyChina** [comment]
the same question, any answer?

**Comment by Eeuro** [comment]
HI,
Remove any setFlash(true) in your onCreate method. then go to onResume() and right below mScannerView.startCamera() add the following:
mScannerView.postDelayed(new Runnable() {
            @Override
            public void run() {
                mScannerView.setFlash(true);
            }
        }, 500);
If the flash still launches too quick, replace 500 with 1000.
Cheers!
