### ISSUE TITLE
Partial screen view

### ISSUE THREAD

**Issue by KennyGoers** [dm77/barcodescanner#226]
Is a partial screen view supported at all?

I get very strange behaviours when trying to do a partial view. In 1.8.4 is shoves the entire camera view into the height of the view I create, in 1.9 it seems to size it OK, but forces the entire screen to house the view in the background, and even then takes scans of non-visible areas. 

Does this library support partial views? It does not appear to.

**Comment by wwdaigo** [comment]
In colors.xml, add those lines and set up with the color as you desire (#0000 for transparent)

<color name="viewfinder_border">#ffafed44</color>
<color name="viewfinder_mask">#60000000</color>
<color name="viewfinder_laser">#ffcc0000</color>
