### ISSUE TITLE
Scanning outside of yellow borders

### ISSUE THREAD

**Issue by kostyabakay** [dm77/barcodescanner#229]
I have this trouble on devices with good camera. Is it the bug or some feature? Because I need scanning only in yellow borders.

**Comment by KostyaBakay** [comment]
I solved my problem by creating class which extends ZBarScannerView and have the same realization, except one line of code:
`var14.setCrop(0, height / 3, width, height / 3);`
[This](http://stackoverflow.com/questions/18918211/how-to-change-area-of-scan-zbar) question was very useful. Please modify your library for this problem.

**Comment by OzTK** [comment]
Hi, I didn't think it would be that simple to do so I gave up. Does it make the scan results more accurate? Could you post the code of the whole class so that it's easier to visualize where you add that line?
Thanks :)

**Comment by KostyaBakay** [comment]
Yes, it becomes more accurate. My own class is copy ZBarScannerView except one line of code and this class extends ZBarScannerView. Please find this class and you will understand. Here is fragment of code with my line:
`Image var14 = new Image(width, height, "Y800");`
`var14.setData(data);`
`// setCrop() parameters: left, top, width, height`
`// http://stackoverflow.com/questions/18918211/how-to-change-area-of-scan-zbar`
`var14.setCrop(0, height / 3, width, height / 3); // Set scanning for the yellow borders`
`result = this.mScanner.scanImage(var14);`

This setCrop method is very uncomfortable, so I hope the developer of this library will add this feature.

**Comment by OzTK** [comment]
Thanks a lot!

**Comment by Bigboer** [comment]
Has this Library been updated to support this request without having to extend the ZBarScannerView yet?

**Comment by GoltsevEugene** [comment]
That helped a lot, imho, it is worth to be included into the lib.
Thanks a lot, @KostyaBakay!

**Comment by KostyaBakay** [comment]
@GoltsevEugene you are welcome :)
