### ISSUE TITLE
Bad scanning results on Android 7.0 and Nexus 5X

### ISSUE THREAD

**Issue by tnedev** [dm77/barcodescanner#232]
Hi, 

Until recently my application was working and scanning great with the Nexus 5X and some beta release of Android 7.0. Recently it stopped working on some of the cases where the QR codes are small. Any idea why is that?

**Comment by annanoell** [comment]
Hi @tnedev , I'm facing the same issue. Could you fix it?
I'm using the ZXingScannerView inside a fragment, and the ResultHandler is never called.

Thank you.

**Comment by tnedev** [comment]
@annanoell 
You cannot scan any code?
What phone/os are you using?

**Comment by annanoell** [comment]
I can only scan codes if the ZXingScannerView is full height, I place it as direct children on the root.
It scans codes when the layout is like this:

`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:background="@color/colorPrimary"
    tools:context="com.smartcitylink.urgellet.fragments.QRFragment">
    <FrameLayout
        android:id="@+id/content_frame"
        android:layout_weight="1"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:id="@+id/relativeLayout2">
        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1"
            android:background="@color/black">

        </RelativeLayout>
        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight=".7"
            android:background="@color/colorPrimary">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/llegeix"
            android:id="@+id/qrText"
            style="@style/InfoTextViewMedium"

            />

        <Button
            android:layout_width="match_parent"
            android:layout_height="60dp"
            style="@style/UrgelletButton"
            android:id="@+id/qrDone"
            android:visibility="gone"
            android:text="@string/he_acabat_reciclar"
            android:layout_alignParentBottom="true"
            android:onClick="acabatReciclar"/>
        </RelativeLayout>
    </LinearLayout>
</RelativeLayout>`

But it doesn't scan anything when the layout is like this:
`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:background="@color/colorPrimary"
    tools:context="com.smartcitylink.urgellet.fragments.QRFragment">


    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:id="@+id/relativeLayout2">
        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1"
            android:background="@color/black">
            <FrameLayout
                android:id="@+id/content_frame"
                android:layout_weight="1"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />
        </RelativeLayout>
        <RelativeLayout
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight=".7"
            android:background="@color/colorPrimary">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="@string/llegeix"
            android:id="@+id/qrText"
            style="@style/InfoTextViewMedium"

            />

        <Button
            android:layout_width="match_parent"
            android:layout_height="60dp"
            style="@style/UrgelletButton"
            android:id="@+id/qrDone"
            android:visibility="gone"
            android:text="@string/he_acabat_reciclar"
            android:layout_alignParentBottom="true"
            android:onClick="acabatReciclar"/>
        </RelativeLayout>
    </LinearLayout>
</RelativeLayout>
`

The thing is that I need the scanning preview in the top half of the screen.
I am testing with a Nexus 5X - 7.1.1 (not working on half screen layout) and a Samsung A3 6.0.1 (working both ways)

**Comment by Cyborg101** [comment]
I'm facing the same issue, Have you found a solution?

**Comment by alikamts** [comment]
same here +1

**Comment by dm77** [comment]
Fixed Nexus 5x portrait scanning issue in v 1.9.8
