### ISSUE TITLE
Data Matrix not working

### ISSUE THREAD

**Issue by bogdanstanga** [dm77/barcodescanner#233]
I have the default formats enabled (all formats) but it would not scan DATA MATRIX.

Any help?

Thank you.

**Comment by satornjanac** [comment]
Same for me. I've been using 1.8.4 in my app and it worked just fine. Now data matrix is scanned always as UPC_E.

Any help?

Thanks in advance

**Comment by arrowoliver** [comment]
Using the default config, but the data matrix is not working.
Any other configuration needed for enabling it or something else may be?

**Comment by arrowoliver** [comment]
Not sure if you guys need it or not anymore but use 
compile 'me.dm7.barcodescanner:zxing:1.9.8' 
instead of 
compile 'me.dm7.barcodescanner:zbar:1.9.8'
Then it will work
