### ISSUE TITLE
I add a title, then it can't scan

### ISSUE THREAD

**Issue by wybilold1999** [dm77/barcodescanner#238]
my XML:
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/black"
    android:orientation="vertical" >

```
<RelativeLayout
```

   android:layout_width="match_parent"
    android:layout_height="54dp">

```
    <TextView
        android:id="@+id/ui_qrcode_scanner_title"
        style="@style/ActionBar_Title"
        android:text="scan" />
</RelativeLayout>

<me.dm7.barcodescanner.zxing.ZXingScannerView
    android:id="@+id/ui_qrcode_scanner_ZXingScannerView"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
</me.dm7.barcodescanner.zxing.ZXingScannerView>
```

</LinearLayout>

Activity is example。san don't work!!!!  why?

**Comment by rcpfuchs** [comment]
I noticed that the zbar scanner will not work on some devices if the ScannerView is not in fullscreen. Try to use a FrameLayout and have a look that  ZXingScannerView is allways fullscreen.
