### ISSUE TITLE
ZBar remove the viewfinder

### ISSUE THREAD

**Issue by marksalpeter** [dm77/barcodescanner#239]
Hi! I wrote my own viewfinder. How do i remove the one that this comes with when I import through gradle?

**Comment by OzTK** [comment]
Hi! To actually apply your viewfinder, you have to override the default one when instantiating you Scanner View:
```java
mScanner = new ZbarScannerView(getContext()) {
    @Override
    protected IViewFinder createViewFinderView(Context context) {
        return new MyCustomViewFinder(context);
     }
};
```

**Comment by marksalpeter** [comment]
Nope, that did the trick. Thanks!
