### ISSUE TITLE
High preview resolution in small sized ZxingScannerView

### ISSUE THREAD

**Issue by akhatriST** [dm77/barcodescanner#240]
Hi, I am using this library to scan QR codes. 
I have fixed the width and height of the ZxingScannerView to 150dp, and placed it in center. By doing this, I am facing a problem as I have reduced the size of the view, the camera resolution also gets reduced, which makes the scan very difficult.

These are Samsung Galaxy s4 stats
Full screen Camera preview, 1080x1920 resolution
Reduced size, 480x320 resolution

The question is how can I get 1080x1920 resolution, in a small sized view?

Thanks in advance

**Comment by marksalpeter** [comment]
Yea, I noticed that this also seems to be impacting the ability for zxing to detect barcodes in the image. That's what I suspect, anyway.
