### ISSUE TITLE
this qrcode was not identify with zbar, but zxing is ok.

### ISSUE THREAD

**Issue by bluevalley15** [dm77/barcodescanner#252]
![default](https://cloud.githubusercontent.com/assets/11980247/19800119/da600c02-9d2c-11e6-9f83-55d7aa0975c4.jpg)

**Comment by dm77** [comment]
Thank you for reporting. Unfortunately this library just uses the ZBar library behind the scenes. So I recommend contacting Zbar authors. See their info in credits section in README
