### ISSUE TITLE
Camera is being used after Camera.release() was called

### ISSUE THREAD

**Issue by yummyChina** [dm77/barcodescanner#256]
I dont know why, I just click back button, and finish() the  activity then it crashed, any one can help me?

**Comment by CoolMind** [comment]
@yummyChina, what is written in the activity, especially in onPause method?

**Comment by yummyChina** [comment]
nothing, I copy almost the same code from demo .
and I found that the real crash reason was not the error log  mentioned in the issue.
I have solved the crash problem,But I have't configure out the reason of error log about camera.
