### ISSUE TITLE
Activity blinks for a second or two then the camera starts

### ISSUE THREAD

**Issue by i-m-aman** [dm77/barcodescanner#263]
i have 4 fragment inside activity using FragmentPagerAdapter, first fragment is where i am scanning the QR Code. 
The thing is whenever i open the activity, the ## whole screen blinks for a second or two and then the camera starts. it happen on devices like Moto G, Xiaomi Redmi but high end devices like One Plus X doesnt seen to have the problem.

**Comment by MohamedElgendyGits** [comment]
hey @deathstroke007  did you find a solution to this issue ??

as i am experiencing the same case now !! 
i have viewpager with 3 pages the first one is ScannerView that led to blink the screen for two seconds even if swiping between pages from and to the ScannerView is slow , i don't know how to fix this.

**Comment by abhilash007** [comment]
as i am experiencing the same case now !!
