### ISSUE TITLE
Please Use Tag Release

### ISSUE THREAD

**Issue by DanieleBelfiore** [dm77/barcodescanner#264]
Hello,
thanks for your developments.

Only one thing I would suggest to you: you could use tag release for every new release commited.

This behaviour permit to us to find more quickly the new releases and even your GitHub page is more standard for GitHub specifications.

Really appreciate that.

Thanks in advance.

![screenshot](https://cloud.githubusercontent.com/assets/10231360/20877349/58b2cf3c-bac8-11e6-8f4d-32a69e5d8780.png)

**Comment by dm77** [comment]
@DanieleBelfiore Thank you so much for the suggestion. That is a good idea. I will make sure to do this for future releases.
