### ISSUE TITLE
photo album 

### ISSUE THREAD

**Issue by yaleidev** [dm77/barcodescanner#266]
hello:
how to selected a photo from photo album ?scan qrcode?what's way?
please.

**Comment by yaleidev** [comment]
hello,please...

**Comment by yaleidev** [comment]
The author?@dm77

**Comment by dm77** [comment]
Hi @yaleidev I am sorry for the delay and I unfortunately do not fully understand your request, but I will give it a shot. If you are trying to decode the contents of a image in the photo library, you have to directly deal with zxing APIs like mentioned in this post http://stackoverflow.com/questions/18863466/reading-qrcode-with-zxing-in-java. You might also be interested in looking at the code in https://github.com/dm77/barcodescanner/blob/master/zxing/src/main/java/me/dm7/barcodescanner/zxing/ZXingScannerView.java#L92

Hope that is helpful. If not please feel free to reopen the issue. Thank you for your patience.
