### ISSUE TITLE
CameraFragment is stretched out, also never scans?

### ISSUE THREAD

**Issue by ZNickq** [dm77/barcodescanner#27]
This is my code: https://gist.github.com/ZNickq/49605d299dbabb321c28

And the layout file looks like this: https://gist.github.com/ZNickq/aabb05a91bc676f186b3

Basically if the fragment is not fullscreen, the view is stretched out. A library i used on iOS just cropped some parts of the screen, so it maintained a good aspect ratio, any way to do this here too? Or does anyone have any code to make the fragment maintain its aspect ratio, while being under certain constraints?

But with the code i provided, it still never scans, even though it is full-screen.. the onresult method never runs, if i point it at a qr code it doesn't do anything, any idea what i'm doing wrong?

**Comment by dm77** [comment]
Version 1.7 fixes the stretching or aspect ratio issue.
