### ISSUE TITLE
Doesn't scan in emulator

### ISSUE THREAD

**Issue by CoolMind** [dm77/barcodescanner#270]
Hello!
When I use an emulator (no matter, AVD or Genymotion) with emulated camera (from notebook, 1.3 mega pixels), I see an image but cannot parse it, 
`public void handleResult(me.dm7.barcodescanner.zbar.Result rawResult) `
is not called.

**Comment by dm77** [comment]
Hi, unfortunately this is such a corner case that I am inclined to close. Sorry, I don't mean to offend you or anything. But if it upsets you, feel free to reopen
