### ISSUE TITLE
Scanning Angle Problem

### ISSUE THREAD

**Issue by ulaserdegor** [dm77/barcodescanner#274]
Hi,
When scanning, you can get results at 90 degree angle.
However, if there is an angled scan in the frame, the result can not be obtained. This is bad for the user.
Earlier I used Zbar and he was immediately getting results at any angle.

Thanks

![screenshot_2017-01-20-09-43-49](https://cloud.githubusercontent.com/assets/12948351/22140612/20b11344-def6-11e6-9c85-1fa4cae7f590.png)

**Comment by wangyuetingtao** [comment]
so it is

**Comment by suryamegham1729** [comment]
Hi Any further improvement on this ?

**Comment by stephenruda** [comment]
I also have this problem
