### ISSUE TITLE
Camera not open dm77 zxing barcodescanner

### ISSUE THREAD

**Issue by ahmaadyunus** [dm77/barcodescanner#275]
I have problem with dm77 zxing barcodescanner while use in device with android 5.0, but on device android 6.0 work normally. i already troubleshoot and rebuild, clean, project, etc and check the permission . need help, what should i do to fix this problem ? thanks

**Comment by Luisfermp18** [comment]
I have the same problem. ¿Do you resolve it now?

**Comment by dm77** [comment]
Hi Guys, please rebuild the zxing-sample app and test on your devices. If you still run into issues, please reopen the issue make sure to include device info.
