### ISSUE TITLE
Not working well on small and large qr codes

### ISSUE THREAD

**Issue by vzaffalon** [dm77/barcodescanner#276]
This library is not working well at all with small and large size qr codes
Tested in many devices, the qr codes that work takes a long time to read

**Comment by dm77** [comment]
Sorry for delay. The qr code handling itself is done by zxing and zbar libraries. So unfortunately we can't do much here. But if you think this is an issue with the library, please feel free to reopen and make sure to include the qr codes you scanned along with the device you tested on. Also please check to see if it has something to do with scanning qr codes in low light environment.
