### ISSUE TITLE
Camera View is rotated

### ISSUE THREAD

**Issue by arielmingrone** [dm77/barcodescanner#278]
Hi, there is a bug on samsung GT-S5830 with android 2.3, it's an old phone and when I try to scan barcode the preview is completely rotated 90 degrees and out of scale because that problem. My phone is in portrait mode, smae as the activity and the target is in landscape. In the above image you can see the problem.
![sc20110103-160251](https://cloud.githubusercontent.com/assets/23727475/22839420/1e02d7b4-efa8-11e6-939d-d5999b5b4c53.png)

**Comment by dm77** [comment]
Thank you for reporting. I will see what I can do.
