### ISSUE TITLE
When I open activity, the screen will flashed.

### ISSUE THREAD

**Issue by ChouCC** [dm77/barcodescanner#279]
When I open activity, the screen will flashed.
Just like open the activity and reopen camera preview again.
Not so smooth.
How can I fix it?
Thanks.

**Comment by dm77** [comment]
Do you mean that there is a lag when opening the camera preview?

**Comment by ChouCC** [comment]
Yes, just like that.
when one activity "A" is start activity to camera preview,  there will be like: A start activity -> camera preview -> A -> camera preview.

**Comment by Jorikua** [comment]
Same behaviour. It doesn't happen on newer devices. When you add view to framelayout, there's a time gap where surfaceview is inflating. During this gap there is a "hole" in android window and you can see a previous activity from stack. I think there's a need in surface callback from within inner classes to handle this situation.

**Comment by iceuncle** [comment]
I have the same issue. Has any solution?
