### ISSUE TITLE
E/ZBarScannerView: java.lang.RuntimeException: Camera is being used after Camera.release() was called

### ISSUE THREAD

**Issue by BigWattanachai** [dm77/barcodescanner#294]
I just open scanner simple activity and click back button then it throws this error  "E/ZBarScannerView: java.lang.RuntimeException: Camera is being used after Camera.release() was called"  p.s. My phone is Huawei P9.

**Comment by ftgqzhengkai** [comment]
me,too! p.s. My phone is Huawei Honor 8 Lite.

**Comment by ftgqzhengkai** [comment]
`E/ZXingScannerView: java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                                                               java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                                                                   at android.hardware.Camera.setHasPreviewCallback(Native Method)
                                                                                   at android.hardware.Camera.setOneShotPreviewCallback(Camera.java:885)
                                                                                   at me.dm7.barcodescanner.zxing.ZXingScannerView.onPreviewFrame(ZXingScannerView.java:167)
                                                                                   at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1204)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                   at android.os.Looper.loop(Looper.java:156)
                                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)`
me,too! p.s. My phone is Huawei Honor 8 Lite.

**Comment by richin13** [comment]
Hello, this can be solved by overriding the `onStop` method of the Activity so that it looks roughly like this:

```java
    @Override
    protected void onStop() {
        super.onStop();
        mScannerView.stopCamera();
    }
```

That fixed it for me.

**Comment by ftgqzhengkai** [comment]
@richin13 ` @Override
    public void onPause() {
        super.onPause();
        mScannerView.stopCamera();
    }`
I have followed the example overriding the`onPause`。

**Comment by richin13** [comment]
@ftgqzhengkai , overriding `onPause` didn't work for me. Did it work for you?

**Comment by ftgqzhengkai** [comment]
@richin13 yes，on other phone it work .In Huawei Honor 8 Lite  didn't work .

**Comment by richin13** [comment]
@ftgqzhengkai, I'm using a Huawei P8 Lite, overriding `onPause` doesn't seem to work but overriding `onStop`does. Did you try with onStop?

**Comment by ftgqzhengkai** [comment]
@richin13 Let me have a try.

**Comment by 1037390459** [comment]
I tried to call stopCamera() on OnStop(),but it didn't work

**Comment by g19980115** [comment]
I add this:`@Override
    protected void onDestroy() {
        super.onDestroy();
        mScannerView.stopCamera();           // Stop camera on pause
    }` it works

**Comment by kakashysen** [comment]
I try added `mScannerView.stopCamera();` on `onPause` , `onDestroy` and `onStop` and does not work! more ideas ?

**Comment by g19980115** [comment]
@kakashysen try this:
```Java
@Override
    protected void onDestroy() {
        super.onDestroy();
        mScannerView.stopCameraPreview();
        mScannerView.stopCamera();           // Stop camera on pause
    }
```

**Comment by kakashysen** [comment]
@g19980115 Not work 😞  the exception still happens

**Comment by romuloum1** [comment]
@kakashysen  try this:

``    @Override
    public void onPause() {
        mScannerView.stopCameraPreview(); //stopPreview
        mScannerView.stopCamera();

        super.onPause();
    }

    @Override
    public void onDestroy() {
        mScannerView.stopCameraPreview(); //stopPreview
        mScannerView.stopCamera();
        mScannerView.destroyDrawingCache();

        super.onDestroy();
    }

    @Override
    public void onStop() {
        mScannerView.stopCameraPreview(); //stopPreview
        mScannerView.stopCamera();

        super.onStop();
    }

**Comment by Ashwani270292** [comment]
Not any of the provided solutions are working for me...in another activity when i am trying to use camera, it gives RunTimeException: Cannot connect to camera service.

Are there any more solutions??

**Comment by KfearO** [comment]
Hi all
I had the same exception, well the exception is a bit confusing since its happening right after pressing back, so I asked myself how can it be that the "Camera is being used" so I understand that once you press the back button the ZXing code calls xxx.release() then the code goes to the "handleResult(Result result)" method, in this method I had xxx.stopCamrea().  obviously you can't call "stop" (use) once the camera is "released" so I used try-catch like so and the issue is solved:

```
@Override
 public void handleResult(Result result) {
            resultBarCode = result.getText();
            setContentView(R.layout.activity_main);
            try {
                scannerView.stopCamera();
            } catch (Exception ex) {
                Log.e("scannerView.stopCamera:", ex.toString());
            }
............
}
```
@BigWattanachai If you haven't solved it yet, I hope it would help

**Comment by mlunap** [comment]
> @kakashysen try this: add ` mScannerView.stopCameraPreview(); //stopPreview`
> 
> ```java
> @Override
>     protected void onDestroy() {
>         super.onDestroy();
>         mScannerView.stopCameraPreview(); //stopPreview
>         mScannerView.stopCamera();           // Stop camera on pause
>     }
> ```

Hi,

In my case, it did not work. I have reviewed the problem and the only temporary solution I found was the following:

 ```java
@Override
    public void onStop() {
        super.onStop();
        barLocation.setResultHandler(null);//prevent Camera is being used after Camera.release() was called
        barLocation.stopCamera();
    }
```
The problem is originating because despite calling "stopCamera" the thread that validates the image is still running. Then to avoid the error again the Handler.

  ```java
public class CustomZXingScannerView extends BarcodeScannerView { //......
public void onPreviewFrame(byte[] data, Camera camera) {
        if (this.mResultHandler != null) {
            try {
                Camera.Parameters parameters = camera.getParameters();
                Camera.Size size = parameters.getPreviewSize();
                int width = size.width;
                int height = size.height;
                if (DisplayUtils.getScreenOrientation(this.getContext()) == 1) {
                    int rotationCount = this.getRotationCount();
                    if (rotationCount == 1 || rotationCount == 3) {
                        int tmp = width;
                        width = height;
                        height = tmp;
                    }
                    data = this.getRotatedData(data, camera);
                }
                //..code for valir QRCode...//Validation the image takes a few seconds and the code runs independently despite having called stopCamera.
                if (rawResult != null) {
                    Handler handler = new Handler(Looper.getMainLooper());
                    Result finalRawResult = rawResult;
                    handler.post(() -> {
                        ResultHandler tmpResultHandler = this.mResultHandler;
                        this.mResultHandler = null;
                        this.stopCameraPreview();
                        if (tmpResultHandler != null) {
                            tmpResultHandler.handleResult(finalRawResult);
                        }
                    });
                } else {
                    if(mResultHandler != null) // prevent Camera is being used after Camera.release() was called
                        camera.setOneShotPreviewCallback(this);
                }
            } catch (RuntimeException var33) {
                Log.d(TAG, var33.toString(), var33);
            }
        }
    }
```

It is not the best solution but it is working for me. I hope to find a better salucion.

Psdt: Excuse me for my English
