### ISSUE TITLE
Reads Barcode, Then Freezes in handleresult()

### ISSUE THREAD

**Issue by lennycode** [dm77/barcodescanner#296]
The ZX play store app works fine, along with other apps using that ZX landscape view.

It will scan a barcode, and freeze the picture when it reaches the result callback. If I put a breakpoint in the `handleresult() ` callback I can see the data. I tried `stopCamera()` and `resumeCameraPreview()`

I also have issues with the embedded zx library. It will just keep blinking (like attempting to read) and never  return to the the callback.  Maybe some common bug there?

Device is LG G3

**Comment by dm77** [comment]
Hi @lennycode Are you able to replicate with the zxing-sample app as well?

**Comment by lennycode** [comment]
I will try the sample app. I ended up compiling the raw zx library and using it in landscape, works perfect, and users don't have to worry about a missing intent or downloading other apps.  May eventually use Vision, my client wants it but we are concerned about the free space requirement to install it.

Here were my troubles with embedded:
https://github.com/journeyapps/zxing-android-embedded/issues/289
