### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by psohm** [dm77/barcodescanner#302]
Hello
when I try to use it in my app in portrait mode
it keeps the portrait and the scan zone is very small
![screenshot_2017-04-19-17-19-24](https://cloud.githubusercontent.com/assets/5886652/25188055/149187ae-2525-11e7-9649-ab99c74f1a54.png)

Is it possible to force landscape on your module and then come back in my good old portrait mode ?

regards

**Comment by dm77** [comment]
@psohm Hi seems like you want to be able to increase the view finder size. Please take a look at #80
