### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by voviks21** [dm77/barcodescanner#303]
Hello! How to add this in my app? I'm using android studio and i don't know how to install this api.

**Comment by richin13** [comment]
Hello you!
The installation process is quite simple:

In you **build.gradle** and the following line:

```
compile 'me.dm7.barcodescanner:zxing:1.9.1'
```
Once you add that line, Android Studio will detect that changes were made to the build.gradle file and will tell you that the project need to be synchronized agan. Once you synchronize the project the library will be installed and available for use.

**Comment by voviks21** [comment]
Thanks for explanation!
But can i install it in Eclipse? 
(i want make small size application, in Studio its impossible big size 1.5 Mb against 48 Kb Eclipse)
Also, is there a way to call scanner activity repeatedly, every 2 seconds, for example? Or not close scan window until some number of codes will be scanned and pause for 2 seconds after each scan

**Comment by dm77** [comment]
@richin13 Thank you for taking care of that.

@voviks21 Don't have plans to support Eclipse at this time. But feel free to clone the project and probably hack something from there. Sorry about that :(
