### ISSUE TITLE
 Camera view is stucked to old captured image.

### ISSUE THREAD

**Issue by axiom88-guru** [dm77/barcodescanner#304]
I have created page with ZXingScannerView and it successfully scan the code on first page and return the result to other page. Issue arise when I tap on back navigation to reopen the camera scan view. It shows old static captured image instead of camera scanning view. Furthermore this behavior is ambiguous, sometimes camera view appears and it again scan the barcode successfully.

**Comment by dm77** [comment]
@axiom88-guru Are you able to replicate this with the samples? If not, then probably something to do with your code. Make sure to stop the camera onPause.
