### ISSUE TITLE
The camera was blurry and no two-dimensional code was scanned

### ISSUE THREAD

**Issue by yy4556028** [dm77/barcodescanner#306]
When I wrapped the ToolBar and ZXingScannerView containers with LinearLayout, the camera was blurry and no two-dimensional code was scanned.
Activity's theme has these
<item name="windowActionBar">false</item>
<item name="windowNoTitle">true</item>

**Comment by dm77** [comment]
Hi @yy4556028. Do you have a code snippet that can replicate the bug? And also can you make sure to include the device info? Thank you.

**Comment by yy4556028** [comment]
LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"

    include
        layout="@layout/toolbar" 

    FrameLayout
        android:id="@+id/activity_scan_frame"
        android:layout_width="match_parent"
        android:layout_height="match_parent" 

LinearLayout

**Comment by cilvet** [comment]
Having the same problem here, except it doesn't work properly with FrameLayout either. The only device it seems to happen in is my Nexus 6p so we might have found a pattern here

**Comment by pawarprasad37** [comment]
Hi @yy4556028 @cilvet  i'm facing a similar issue with Honor device. Tried wrapping the ZXingScannerView in FrameLayout but issue is still there. Did you do anything else to resolve it? I have a RelativeLayout as the root and then a FrameLayout inside which the ZXingScannerView is placed. Any help is appreciated!
