### ISSUE TITLE
Area box scan barcode more smaller

### ISSUE THREAD

**Issue by mohamadakmalshukri** [dm77/barcodescanner#309]
I want make area for scan barcode become smaller.. How can i do that ?

**Comment by dm77** [comment]
Hey @mohamadakmalshukri . Take a look at this https://github.com/dm77/barcodescanner/pull/80 and see if that helps

**Comment by mohamadakmalshukri** [comment]
@dm77 I already do like #80 but i don't know where to make green border (size area scan) more small height

**Comment by akmalshukri** [comment]
i use me.dm7.barcodescanner:zbar:1.9.1
