### ISSUE TITLE
I want resize scanner area like this image.. I want like left side which is no 1. The height more small compare to image no 2. How can i do like that ?

### ISSUE THREAD

**Issue by mohamadakmalshukri** [dm77/barcodescanner#310]
![sss](https://cloud.githubusercontent.com/assets/28430150/25777985/243b4274-3323-11e7-8244-b37ff3a4b4de.PNG)

**Comment by dycasxe101** [comment]
me too

is there anyone can explain or give some suggestion?

**Comment by dm77** [comment]
Here 

If you are looking to customize ViewFinder, see #80  
If you are looking to scale the camera to fit the screen, you can call setShouldScaleToFill(true)

**Comment by dycasxe101** [comment]
thanks owner @dm77 . Alhamdulillah yesterday, my problem was clear. 

but now the problems is, SDK, in kitkat and lollipop, the camera didn't show up. and know i research again. Fighting.

i hope if u online, give some suggestion again. Big thanks
