### ISSUE TITLE
Most QRCode is work well but this one

### ISSUE THREAD

**Issue by ziling9527** [dm77/barcodescanner#311]
@dm77 , thanks for you work，you save me a lot of time!
the library work well for most qrcode,but this one can not decode,can you give me some advice?
![barcode](https://cloud.githubusercontent.com/assets/26479902/26026232/52c37e84-382a-11e7-8c98-8b0041861e27.png)

**Comment by dm77** [comment]
Hi @ziling9527 - The scanning implementation relies on the awesome zxing project (https://github.com/zxing/zxing). My understanding is that it only supports qrcodes on white background or the inverse qr codes. I even tested your qr code with the official barcode scanner app from zxing and it didn't work. You might have better luck submitting a issue with zxing project.

**Comment by dm77** [comment]
Sorry I couldn't help you more on this :(
