### ISSUE TITLE
can you support for TextureView？

### ISSUE THREAD

**Issue by sungerk** [dm77/barcodescanner#314]

**Comment by dm77** [comment]
HI @sungerk . What would be the advantages in supporting a TextureView. What use case do you have in mind?

**Comment by sungerk** [comment]
create a custom scanner view. in usually, we use a page to scan qrcode don't do anything else ，and only has some view about scan.  surfaceview is a terrible choice if you want to use the scan view in a activity with editext or other Input box ,but textureView without these problems, surfaceview cause a lot of problems,such as videoview in  listview.
