### ISSUE TITLE
Callback is not a weak reference

### ISSUE THREAD

**Issue by Dragas** [dm77/barcodescanner#319]
In your readme you suggest that an activity handling the scanner callback should implement `ZXingScannerView.ResultHandler` interface, yet the scanner view itself holds a hard reference (as suggested by `private ZXingScannerView.ResultHandler mResultHandler;`) to it and not a weak one. This might cause a memory leaks and in general is a bad practice to hold a direct reference to a context.

Either suggest anything but an activity implement the callback, or hold a weak reference to it.

**Comment by yuriy-budiyev** [comment]
This is not a problem if reference is not static. The scanner view will be destroyed with the activity or the fragment that holds it.
