### ISSUE TITLE
hello how can i Scan two bar codes at the same time using zbar？thank you

### ISSUE THREAD

**Issue by binzhiyuan** [dm77/barcodescanner#320]
hello how can i Scan two bar codes at the same time using zbar？thank you

**Comment by dm77** [comment]
Hi @binzhiyuan. Scanning multiple codes is currently unsupported. Unfortunately there are no plans to support this feature since it sounds like a corner-case to me. I will reopen the issue if there is high demand for it. Sorry for not being helpful :(
