### ISSUE TITLE
After upgrading to 1.9.3 version - on click of scan and pay white preview screen is shown for few seconds then resume camera

### ISSUE THREAD

**Issue by hemapanjakshram** [dm77/barcodescanner#326]
After upgrading to 1.9.3 version - on click of scan and pay white preview screen is shown for few seconds then camera is getting resumed...happens all the time when i go back and click on scan and pay again

**Comment by rekhaagarwal** [comment]
@dm77 can you please tell me on which release its fixed?

**Comment by rekhaagarwal** [comment]
Hey @dm77 is there any update on above mentioned issue. I am facing it on latest release 1.9.8 as well

**Comment by hemapanjakshram** [comment]
Not fixed yet

**Comment by rekhaagarwal** [comment]
Yeah.. any plan for the above issue fix in next release?

**Comment by mtoday** [comment]
Do you know how to fix it?

**Comment by yassineKharraz** [comment]
hey guys ! i am facing the same issue ! is there any solution for this ?
