### ISSUE TITLE
kotlin无法使用

### ISSUE THREAD

**Issue by linxueyi2230** [dm77/barcodescanner#327]
同样的代码思路使用Java可以扫描二维码，使用kotlin则无法扫描

**Comment by dm77** [comment]
Are you saying the library doesn't work with Kotlin? I can't imagine that could be the case. Do you have example code?

**Comment by linxueyi2230** [comment]
This is the code written in kotlin and Java. Please let me know if there is any mistake

kotlin：
class ZXingActivity : AppCompatActivity(), ZXingScannerView.ResultHandler {

    val TAG = "ZXingActivity"

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_zxing)
        xsv_scanner.setResultHandler { this }
        xsv_scanner.setAutoFocus(true)

    }

    override fun onStart() {
        super.onStart()
        xsv_scanner.startCamera()
    }

    override fun onStop() {
        super.onStop()
        xsv_scanner.stopCamera()
    }

    override fun handleResult(result: Result?) {
        xsv_scanner.resumeCameraPreview { this }
        if (result == null) {
            return
        }

        xsv_scanner.stopCamera()
        var text = result.text
        tv_result.text = text

        Log.i(TAG,text)
        tv_result.text = text
    }

}

Java：
public class ScannerActivity extends AppCompatActivity implements ZXingScannerView.ResultHandler{
    private ZXingScannerView xsv_scanner;
    private TextView tv_result;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_zxing);

        tv_result = (TextView) findViewById(R.id.tv_result);
        xsv_scanner = (ZXingScannerView) findViewById(R.id.xsv_scanner);
        xsv_scanner.setResultHandler(this);
        xsv_scanner.setAutoFocus(true);

    }

    @Override
    protected void onStart() {
        super.onStart();
        xsv_scanner.startCamera();
    }

    @Override
    protected void onStop() {
        super.onStop();
        xsv_scanner.stopCamera();
    }

    @Override
    public void handleResult(Result result) {
        xsv_scanner.resumeCameraPreview(this);
        if (result ==null){
            return;
        }

        xsv_scanner.stopCamera();

        Log.i("Scanner",result.getText());
        tv_result.setText(result.getText());


    }
}

**Comment by ntsik** [comment]
@linxueyi2230 You're passing a no-op lambda into `xsv_scanner.setResultHandler { this }` and `xsv_scanner.resumeCameraPreview { this }`. Replace your curly brackets with parentheses and things should work.

To elaborate, `xsv_scanner.setResultHandler { this }` is equivalent to:

```
xsv_scanner.setResultHandler(new ZXingScannerView.ResultHandler() {
    @Override
    public void handleResult(Result result) {
        this; // No-op
    }
});
```

Disclaimer: I haven't tested this. I just happened into this ticket and have seen this mistake before.

**Comment by dm77** [comment]
Thank you @ntsik
