### ISSUE TITLE
Auto fash mode

### ISSUE THREAD

**Issue by KrajncJ** [dm77/barcodescanner#329]
Hi!

I would need a flash to be enabled on the user's request, Currently I initialized it as enabled, but I would need a button or auto flash mode.

Currently I am usig this onCreate, but cannot disable it during scan:

`mScannerView.setFlash(true);`

**Comment by dm77** [comment]
Hmm, were you able to replicate with the sample app (zxing-sample)? Specifically, with the FullScannerFragment (https://github.com/dm77/barcodescanner/blob/master/zxing-sample/src/main/java/me/dm7/barcodescanner/zxing/sample/FullScannerFragment.java)

**Comment by KrajncJ** [comment]
I am using React-Native node_module (https://www.npmjs.com/package/react-native-zbar-android).
This module uses this project as dependency. 

```java
.... 
import me.dm7.barcodescanner.zbar.Result;
import me.dm7.barcodescanner.zbar.ZBarScannerView;

public class ZbarScannerActivity extends Activity implements ZBarScannerView.ResultHandler {
    private ZBarScannerView mScannerView;

    @Override
    public void onCreate(Bundle state) {
        super.onCreate(state);
        setContentView(R.layout.activity_zbar_scanner);
        ViewGroup contentFrame = (ViewGroup) findViewById(R.id.content_frame);
        mScannerView = new ZBarScannerView(this);
        /* Enabling flash here */
	mScannerView.setFlash(true); 
        contentFrame.addView(mScannerView);
    }
```

So the project is included in `build.gradle`

```
dependencies {
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.facebook.react:react-native:+'
    compile 'me.dm7.barcodescanner:zbar:1.9.3'
}
```

So I would have to include it as library. This is my folder in `node_modules/react-native-zbar-android/android`

![image](https://user-images.githubusercontent.com/16381836/28202376-629a924a-6875-11e7-8823-438cb6ce5430.png)

I will need a change in camera parameters in file `BarcodeScannerView.java` in method `setFlash(boolean flag)`  instead of `FLASH_MODE_TORCH` to `FLASH_MODE_AUTO.` Any Idea how to include project or maybe create PR with more option in setFlash method?

```java
public void setFlash(boolean flag) {
        mFlashState = flag;
        if(mCameraWrapper != null && CameraUtils.isFlashSupported(mCameraWrapper.mCamera)) {

            Camera.Parameters parameters = mCameraWrapper.mCamera.getParameters();
            if(flag) {
                if(parameters.getFlashMode().equals(Camera.Parameters.FLASH_MODE_TORCH)) {
                    return;
                }
                parameters.setFlashMode(Camera.Parameters.FLASH_MODE_TORCH);
            } else {
                if(parameters.getFlashMode().equals(Camera.Parameters.FLASH_MODE_OFF)) {
                    return;
                }
                parameters.setFlashMode(Camera.Parameters.FLASH_MODE_OFF);
            }
            mCameraWrapper.mCamera.setParameters(parameters);
        }
    }

```

Thanks.
