### ISSUE TITLE
Scanner can't autofocus / autofocus no any action on device

### ISSUE THREAD

**Issue by mp-kelvincheung** [dm77/barcodescanner#330]
i have set mScannerView.setAutoFocus(true);
but device still cant autoFocus

**Comment by dm77** [comment]
Hi @mp-kelvincheung , is it on a single device or has it been the case on all your devices?

**Comment by Pavle37** [comment]
@dm77  I am having the same problem, but only with Huawei phones, p9 and p9 lite. It's not that it cannot autofocus, but rather the image is so pixelized that it cannot parse the QR Code.

**Comment by AsyrafKman** [comment]
My side also facing the same issue. Cannot auto focus and crash with Huawei P9.

**Comment by anastaciakv** [comment]
I'm also facing this problem with Huawei phones (p9 and p10)

**Comment by olejon** [comment]
I see the same problem in the emulator (using my webcam) and on a Samsung Galaxy S II (used for testing purposes) running LineageOS Android 7.1.2. Haven't tested on my Nexus 5 yet (also running LineageOS Android 7.1.2).

**Comment by dm77** [comment]
Seems like Hauwei phones in general have a ton of issues with this library. Will close this ticket and try to fix as part of 2.0 update (#332)

**Comment by KoTius** [comment]
Experienced this issue on Pixel 2 XL.
This happens if i lay down phone on table with enabled cameraPreview for a few seconds. After that autofocus breaks.
