### ISSUE TITLE
Possible improvements/changes for 2.0

### ISSUE THREAD

**Issue by dm77** [dm77/barcodescanner#332]
Will keep adding to the list as I remember, but here are a few things on my mind for now:

* Evaluate Camera2 API and integration if it makes sense (Fill hopefully fix a slew of Hauwei device issues 
* Merge in MobileVision PR:  #286. Thank you TonyTang
* Merge in fix for Nexus 5x: #315 (Update: Still doesn't work apparently, see #346)
* Cleanup code around ScannerView attributes. Currently some attributes are set using the setters and some are available to setup with the custom view attributes
* Evaluate TextureView instead of SurfaceView for the CameraPreview
* May be add support for requesting Camera permissions 
* ViewFinder customization code needs some work. 
* Add support for completely removing the view finder and do something similar to Google Mobile Vision library sample.
* Better documentation

**Comment by kwojewoda** [comment]
It would be great to have this issue solved:  Merge in fix for Nexus 5x: #315 .... , thanks!
