### ISSUE TITLE
Lower surface view causes bad camera quality on Huawei phones

### ISSUE THREAD

**Issue by Pavle37** [dm77/barcodescanner#333]
In the sample project, I've changed the activity_simple_scanner_fragment.xml to look like this

`<RelativeLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <fragment
        android:id="@+id/scanner_fragment"
        android:name="me.dm7.barcodescanner.zxing.sample.SimpleScannerFragment"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_below="@+id/toolbar"
        android:layout_weight="1" />

    <android.support.v7.widget.Toolbar
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_gravity="top"
        android:background="@color/actionbar_opacity"
        android:minHeight="?attr/actionBarSize"
        app:theme="@style/TransparentToolbar" />
</RelativeLayout>`

I've added the fragment to be below the toolbar.

And that cuases extremely bad camera quality on Huawei phones. I've tested this on Samsung s7, s8, HTC Desire 625 and few others including p9 and p9 lite, and it seems to me that only Huawei phones have this issue. How do we fix this?

**Comment by dm77** [comment]
Will fix in #332
