### ISSUE TITLE
EAN 13 barcode scanned wrong sometimes gives 8 digit Number with upc type

### ISSUE THREAD

**Issue by akanksha1411** [dm77/barcodescanner#335]
App has zbar scanner 1.9.3 and when user scan EAN 13 barcode it gives same 8 digit no. Sometimes it scans well rest of the times it gives this 8 digit no. 

Barcode is scanned in China Location.

**Comment by NorbertSzydlowski** [comment]
+1

**Comment by dm77** [comment]
It is a bug in zbar

**Comment by jicg** [comment]
I also have this problem, how to solve?
