### ISSUE TITLE
zxing-sample can't scan

### ISSUE THREAD

**Issue by ouyangzn** [dm77/barcodescanner#338]
zxing-sample can't scan but ScalingScannerActivity
zbar-sample also can't scan but FullScannerFragment

used version : 1.9.6

mobile : honor 6(H60-02 EMUI4.0 Android 6.0)

**Comment by ouyangzn** [comment]
1.9.3 is ok

**Comment by ouyangzn** [comment]
In 1.9.6 , google pixel is also incorrect.

**Comment by jdsingh** [comment]
Also not working on Motorola G4 plus.

**Comment by dm77** [comment]
I just tested on a Google Pixel and everything works fine. 1.9.6 is no different from 1.9.4.

**Comment by dm77** [comment]
Sorry closed prematurely. I do have things working on 6 test devices, but I also do see a code regression.

**Comment by dm77** [comment]
I just released 1.9.7 which I believe fixes the issue. Can any of you please confirm? Sorry again for the trouble

**Comment by jdsingh** [comment]
1.9.7 is working fine on Motorola G4 plus and Samsung Iris Tab.

**Comment by dm77** [comment]
Thank you for testing @jdsingh

**Comment by ouyangzn** [comment]
1.9.7 is working fine on honor 6(H60-02 EMUI4.0 Android 6.0) and Google pixel
