### ISSUE TITLE
QR Code not working on 1.9.6

### ISSUE THREAD

**Issue by caramelWaffle** [dm77/barcodescanner#339]
I try this version but QR Code scanning now working now.
I already used version 1.9.3 its work fine

**Comment by goujonbe** [comment]
It doesn't work since the 1.9.5 version.

**Comment by dm77** [comment]
The breaking change in 1.9.5 has been reverted and 1.9.6 works fine on all the devices I tested so far

**Comment by dm77** [comment]
Sorry closed prematurely. I do have things working on 6 test devices, but I also do see a code regression.

**Comment by dm77** [comment]
I just release 1.9.7 which I believe fixes the issue. Can any of you please confirm? Sorry again for the trouble

**Comment by dm77** [comment]
Closing as a duplicate of #336

**Comment by caramelWaffle** [comment]
@dm77  1.9.7 works fine. Thanks

**Comment by dm77** [comment]
Thank you so much for confirming @caramelWaffle

**Comment by goujonbe** [comment]
Indeed it works on my device @dm77. But there is still a problem. We can't scan a QR code after calling .resumeCameraPreview(yourActivity).
