### ISSUE TITLE
barcode scanned wrong sometimes gives 8 digit Number

### ISSUE THREAD

**Issue by ouyangzn** [dm77/barcodescanner#344]
version : zxing 1.9.7
mobile : Google pixel and honor 6
![qq 20170808184257](https://user-images.githubusercontent.com/8808376/29068443-73cce18c-7c69-11e7-9cb1-5c4d15b026e6.png)

**Comment by dm77** [comment]
Hi @ouyangzn Unfortunately there is not much I can do here since the library only deals with the UI. You might have better luck submitting an issue to the zxing project.
