### ISSUE TITLE
Build Number 1.9.7 , doesn't work with android 7.1.2 in Nexus 5x . 

### ISSUE THREAD

**Issue by ahmedeltaher** [dm77/barcodescanner#349]
Just checkout the sample code and run it in any device with android 7.1.2 , the barcode detection doesn't work !.
I tried to debug to understand which kind of .
hint : 
Always result is 0 in class `ZBarScannerView` line `94` .

**Comment by ahmedeltaher** [comment]
I tested Build number 1.9.3 and it works fine . 
that is mean it is new problem generated in build number 1.9.7 .

**Comment by dm77** [comment]
Nexus 5x has a weird camera orientation unfortunately. Will try to fix in 2.0. There have been multiple attempts to fix.

**Comment by dm77** [comment]
Note it will scan fine in landscape mode apparently

**Comment by dm77** [comment]
This should be fixed in 1.9.8. I personally tested this on Nexus 5x device
