### ISSUE TITLE
Is it possible to show the yellow flashing dots?

### ISSUE THREAD

**Issue by willemstoker** [dm77/barcodescanner#35]
When I scan a code with the original ZXing app on android it is showing yellow dot's where it's recognizing a barcode. In my project we need to scan QR codes in a dark enviroment and this will help me determine how well the scanner is performing in low light. And the dots look cool too! Is it possible to enable them with this library too?

Thanks!

**Comment by virmundi** [comment]
I looked at the code for the original ZXing app. I don't think the dots are anything more than a placebo. Also the team that developed the original ZXing require that the UIs that use it not have features that are similiar to theirs, specificially the dots. They hold the trademark on that. 

It is those reasons that I use this plugin. It uses the opensource library without violating the ZXing team's trademark.

**Comment by jjhesk** [comment]
+1
