### ISSUE TITLE
Question: No Preview scan

### ISSUE THREAD

**Issue by MrChriZ** [dm77/barcodescanner#353]
Can this library be used to scan without any preview window at all?
I'd like my activity to be scanning in the background from the moment it's opened.
As we're using QR codes the cameras pick them up so easily that the preview window is not really needed once a user is practiced on where to place it.
Thanks,
Chris.

**Comment by dm77** [comment]
HI @MrChriZ that functionality is unfortunately not supported and is not on the roadmap either. Thank you.
