### ISSUE TITLE
should i put your name in my settings screen ?

### ISSUE THREAD

**Issue by iLov3Java** [dm77/barcodescanner#354]
hi Dushyanth Maguluru !
i'm totally new and i loved your project that using zxing library so much!

i'm sorry for openning this issue but i really need to PLAY SAFE when using this library 

it's under apache License and i read a lot about how to use it 

but believe or not i still don't get it ?

can i just use it for my app which i want to publish or i have to put your name to make users read it in my settings screen ?

**Comment by dm77** [comment]
Hi @iLov3Java Thank you for the nice words. You can use it without having to use my name. May be this FAQ will help.
