### ISSUE TITLE
PDF417 is not recognized

### ISSUE THREAD

**Issue by xlyashuk** [dm77/barcodescanner#356]
Hi,

I have tried to scan PDF417 barcode, but it is not recognized and scanning camera continues running.
I tried several PDF417 samples and non of them worked. 
I use samsung s7 and another barcode types are working fine for me.
I have attached two samples which I tried.

![better_sample_pdf417](https://user-images.githubusercontent.com/14789223/29660895-25e8eae2-88cb-11e7-84b5-aa92d6194de0.png)
![photo_2017-08-23_21-25-14](https://user-images.githubusercontent.com/14789223/29660896-25ee0e00-88cb-11e7-85cb-6d08a9ee6ff1.jpg)

**Comment by dm77** [comment]
Hi @xlyashuk is this on zbar or zxing?

**Comment by xlyashuk** [comment]
Hi @dm77 I'm using zbar

**Comment by dm77** [comment]
Unfortunately zbar doesn't support PDF. See my response in #45

**Comment by xlyashuk** [comment]
PDF407 worked well with ZXing. Thank you.
