### ISSUE TITLE
keeps focusing when the QR code is Clear.

### ISSUE THREAD

**Issue by iLov3Java** [dm77/barcodescanner#357]
i'm having a problem with the Auto Focus , when i test it , the camera keeps focusing forever even if the image is clear . how can i fix this please ?

**Comment by sg552** [comment]
tell us your PHONE's model, vendor,   
tell us your OS, IDE, android SDK. 
and it's better to give us your code, if possible. 

otherwise we don't know how to re-produce the bug.
