### ISSUE TITLE
Attribute "maskColor" already defined with incompatible format.

### ISSUE THREAD

**Issue by kampoengboy** [dm77/barcodescanner#358]
Hello, I have a problem with updating into 1.9.8. I have another library that has an attribute "maskColor" also. When I sync the gradle, it's always says that and I'm stuck with it almost 2 hours. Can anyone give me a solution?

**Comment by kampoengboy** [comment]
I have found my own solution. And I will close it.

Thanks

**Comment by hiepbeos** [comment]
i had same problem :((( help me
