### ISSUE TITLE
when i open qr code view after that start a blank white screen 

### ISSUE THREAD

**Issue by mehulTank** [dm77/barcodescanner#360]
when i open qr code  then open white screen first after that open qr code view. how it is resolve that any possible solution for that please let me know

**Comment by rekhaagarwal** [comment]
I faced the same issue. Any update on the above issue? I am getting white screen for fraction of seconds.
I am using compile 'me.dm7.barcodescanner:zxing:1.9.3'

**Comment by sarthakz9** [comment]
any updates ??

**Comment by dainetdev** [comment]
On Android> = 6, you need to ask for CAMERA permission
