### ISSUE TITLE
在小米6上，无法打开扫描

### ISSUE THREAD

**Issue by hudan2714** [dm77/barcodescanner#362]
在小米6上，无法打开扫描，无法显示扫描框。三星和华为还没有问题。

**Comment by Even201314** [comment]
也许和拍照权限有关

**Comment by sg552** [comment]
（作者是印度人？估计用中文说他们听不懂）
Is your problem resolved? 

I found that it doesn't work on HUAWEI P10.

**Comment by ParfoisMeng** [comment]
@sg552 I testing HUAWEI P10 was OK

**Comment by ParfoisMeng** [comment]
@sg552 有没有什么方法可以实现手动聚焦呢？

**Comment by sg552** [comment]
我不太清楚。　你看一下log, 是不是哪里出错了。我这里用的还挺好，新版本貌似解决了机型不兼容的问题。你下载最新的代码试一下。
