### ISSUE TITLE
Is there posibillity to make camera preview rectangle corner(not border) rounded in ZBar?

### ISSUE THREAD

**Issue by KonradSzewczuk** [dm77/barcodescanner#373]
In the IViewFinder interface there are methods to make rounded border, but is there any way to make the whole rectangle of the scanner rounded? I am making transparent border, so there is none and i don't need the border.

**Comment by rekhaagarwal** [comment]
yeah..I want the same requirement as well. I am also making border transparent as I don't want it. But I need the scanner rectangle corners rounded (without border). Is there any way?

**Comment by rekhaagarwal** [comment]
@dm77 any update on above requirement?

**Comment by scottschmitz** [comment]
I am also experiencing this issue. It appears as though the `cornerRadius` property is _only_ affecting the border.

    <me.dm7.barcodescanner.zxing.ZXingScannerView
      android:id="@+id/scannerView"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      app:squaredFinder="true"
      app:laserEnabled="false"
      app:maskColor="@color/colorDarkBlue"
      app:borderColor="@color/colorPrimary"
      app:cornerRadius="100dp"
      />
![screenshot_20181220-105022_dash 2](https://user-images.githubusercontent.com/1085240/50295461-10f19380-0446-11e9-99fa-c1df84547a63.jpg)

**Comment by naimishvinchhi** [comment]
Hi @scottschmitz  
Is there any update regarding this? I am facing the same issue.

**Comment by scottschmitz** [comment]
I haven't been keeping up on this, and I ended up tweaking our designs to just be more square. At one point I did slim down the corner and then increase the border thickness. Since the lines go outside of the camera view you can mask the corners inside of the rounded corners. It's an option if nothing else.

**Comment by sreejithileaf** [comment]
@scottschmitz i'm also facing this issue. Can you post the code if you don't mind

**Comment by scottschmitz** [comment]
To be completely obnoxious I set the values to be huge to demonstrate my point. 

    <me.dm7.barcodescanner.zxing.ZXingScannerView
        android:id="@+id/scannerView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:laserEnabled="false"
        app:borderColor="@color/colorPrimary"
        app:borderWidth="40dp"
        app:cornerRadius="60dp"
        />

<img width="431" alt="image" src="https://user-images.githubusercontent.com/1085240/65999532-8fff0800-e46b-11e9-92e5-c05f38d6508d.png">

I made it (in my opinion) significatly more reasonable my taming it down to something like this to give it a slight curve.

    app:borderWidth="4dp"
    app:cornerRadius="6dp"

In the spirit of hacktoberfest I might create a PR for this.

**Comment by scottschmitz** [comment]
@sreejithileaf - See above that I opened up a PR to fix this. Hopefully that is helpful to you :)

**Comment by sreejithileaf** [comment]
> @sreejithileaf - See above that I opened up a PR to fix this. Hopefully that is helpful to you :)

Thanks @scottschmitz I'll check it :+1:
