### ISSUE TITLE
java.lang.NoSuchFieldError: No static field AZTEC of type Lcom/google/zxing/BarcodeFormat;

### ISSUE THREAD

**Issue by bembengcs** [dm77/barcodescanner#374]
How to deal with this error, it's seems like huge error. You guys ever heard this error?Everything barcode stuff in my project show this error and mention this file Lcom/google/zxing/BarcodeFormat; Help me please!

**Comment by Hitexroid** [comment]
this is my problem too

**Comment by Hitexroid** [comment]
**solved** .

update zxing to 2.1
[download from here](http://www.java2s.com/Code/Jar/z/Downloadzxing21jar.htm)
