### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method invert()Lcom/google/zxing/LuminanceSource;

### ISSUE THREAD

**Issue by smi22** [dm77/barcodescanner#376]
in class Lcom/google/zxing/PlanarYUVLuminanceSource; or its super classes (declaration of 'com.google.zxing.PlanarYUVLuminanceSource' appears in /data/app/com.sf.quid-2/split_lib_dependencies_apk.apk:classes6.dex) 
When camera open, It shut down after getting this error.This causes crash in app.

**Comment by Hitexroid** [comment]
this error occureds by this line 
`mScannerView.setResultHandler(this);`

any suggestion ?

**Comment by Hitexroid** [comment]
**Solved .**

[download version 2.2](http://repo1.maven.org/maven2/com/google/zxing/core/2.2/) and use it
