### ISSUE TITLE
Alter frame/shape of the viewfinder

### ISSUE THREAD

**Issue by markymc** [dm77/barcodescanner#38]
Hi there,

Many thanks for this awesome library! I'm wondering if there's a way to alter the frame of the viewfinder via the ZBarScannerView class (without forking)? We're exclusively scanning QR codes in our app, and would like the frame to be square instead of landscape.

Thanks in advance for any help!

**Comment by dm77** [comment]
#80 might help. Will merge this weekend.

**Comment by dm77** [comment]
Thanks to @marchelo , his pull request has been now merged in. Changes available in version 1.8
