### ISSUE TITLE
black camera screen after first scan

### ISSUE THREAD

**Issue by KatchS** [dm77/barcodescanner#380]
I wrote a sample code that contains a button that, when pressed, reveal the zxing view and thus show the camera, and, in the handler, I changed back to the layout of the main activity.

it works fine for the first time, but if I click again, the zxing view is shown but the camera is simply black. I have to exit (get out of, not close completely) the app and open again so it will work again.

I tried using the "zXingScannerView.resumeCameraPreview(this);" inside the handler but it didn't help.

**Comment by eihror** [comment]
To do this, the best way is using fragment to add and remove camera every time that you return to activity
