### ISSUE TITLE
BarCode Scanning in Samsung J2 Android version 5.1

### ISSUE THREAD

**Issue by siripermi** [dm77/barcodescanner#383]
Device specific(Samsung J2 Android version 5.1) Qr scan is not working.When we scan any bar-code through this device its staying just ideally but the same bar-code getting scanned by another device

**Comment by kprathap23** [comment]
I have same issue BarCode Scanning in Samsung J3 Android version 5.1 not working

**Comment by Ramkesh9** [comment]
Exact Same with my case in j2 , how could we solve it ?

**Comment by jethitapas** [comment]
same here
