### ISSUE TITLE
error: duplicate value for resource 'attr/borderAlpha' with config

### ISSUE THREAD

**Issue by kalpeshp0310** [dm77/barcodescanner#387]
`borderAlpha` attribute defined in `attrs.xml` colloids with support library version 25.4.0, causing gradle build to fail.

**Comment by the-rs** [comment]
Upvoting it. @dm77 it's very wide-used name, it could be named at least "scannerBorderAlpha". Now I have a name conflict between your library and some other.

**Comment by the-rs** [comment]
@dm77 What do you think of making a prefix to all such resources? Will you accept a PR?
