### ISSUE TITLE
reduce view size

### ISSUE THREAD

**Issue by croccio** [dm77/barcodescanner#39]
HI! If i reduce view size from xml it doesn't recognize any qrcode, while if i set height and width to match_parent it recognize them. How can i do?

**Comment by slaha** [comment]
Here is a patch to solve this issue: https://github.com/dm77/barcodescanner/pull/37/files#diff-0

**Comment by dm77** [comment]
This is now merged in version 1.7.

**Comment by DasCody** [comment]
@dm77 this fixed the issue I was having where the viewfinder was off (lining up with laser wasn't scanning, with barcode above the laser it scanned). Now there are black bars on the left and right of my scanner view though.

**Comment by dm77** [comment]
@DasCody Sorry about that. The black bars are there because the camera preview is trying to be fitted in the available space without being stretched. For best results, one should be using a full screen theme in combination will overlay elements. For example, see #67

**Comment by sainttail** [comment]
Then what about the scan view is in the fragment that also in base activity that will replace fragment (I cannot make scan qr fragment use full screen)

Here is my activity layout
```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <include layout="@layout/actionbar_layout" />

    <FrameLayout
        android:id="@+id/scan_content"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        android:layout_weight="1">

    </FrameLayout>

    <include layout="@layout/tabbar_layout" />
</LinearLayout>
```

scan content will be replace by scan fragment but any way it cannot stretch to fill full screen and it leave black black ground on left and right side

and apart from scan qr fragment I also have many other fragments that will be replaced here also.

How can I solve this?
