### ISSUE TITLE
Scanner Camera Black

### ISSUE THREAD

**Issue by ruhul015** [dm77/barcodescanner#399]
I have attached ZXingScannerView in Framlayout by pragmatically. Scanner camera went Black, nothing to do anything. I have found this issue in **Nexus 5x** with latest Android OS **(8.1.0).**  I have got this issue by using following steps,

01. Open Scanner Fragment by using some button click and scanner camera displayed well and scan QR code.
02. Press home button and app goes to background.
03. Now open app by using recent list and found the BLACK scanner camera. I could not do anything. But it work well if i press back and return Scanner Fragment by using Step 01.

Please let me know the way so that i can fix it

Thanks,

**Comment by niladreeb** [comment]
Experienced the same issue in Pixel 2 XL with Android OS (8.1.0).
