### ISSUE TITLE
Camera focus time hardcoded

### ISSUE THREAD

**Issue by anton8900** [dm77/barcodescanner#400]
now camera focus time is 1000L, but this is not optimal parameter for all phones, some can focus faster, some can't focus in this time

**Comment by abolfazlkalamati** [comment]
see this link 
https://stackoverflow.com/questions/54003150/how-to-improve-the-focus-speed-of-camera/54004787#54004787

**Comment by vinint** [comment]
Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE
but it does not work sometime,for example in XiaoMI camera
the most diffcult is camera1 API tell you suppored.
but the fact ,it does not work on device
