### ISSUE TITLE
Scanning of Hash-QR-Codes from the terminal

### ISSUE THREAD

**Issue by HolgerThyen** [dm77/barcodescanner#404]
I've been trying to scan the following QR-Code with my own Android app, which for now mainly rebuilds the simple scanner zxing sample from the repository. 
![grafik](https://user-images.githubusercontent.com/35269556/34733469-c5878950-f568-11e7-8bb6-552e49093da5.png)
While the sample code can detect this QR-code if the captured image is a bit blurred during re-focusing, my own app does not detect it under the same circumstances. Ordinary QR-codes are working perfectly well. 

Is there an option to set the sensitivity of the scanner I overlooked and might only be set in the sample code?

Regards, Holger

**Comment by thestinger** [comment]
You can generate much better text-based QR codes using Unicode characters. Look at the QR code generator in systemd as an example.

**Comment by thestinger** [comment]
You can display much better QR codes in a Terminal. Look at the QR code generator in systemd.
