### ISSUE TITLE
Version incompatibility with appcompat

### ISSUE THREAD

**Issue by ghost** [dm77/barcodescanner#408]
_compileSdkVersion 27
    defaultConfig {
        applicationId "com.example.packagename"
        minSdkVersion 15
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }_

_implementation 'com.android.support:appcompat-v7:27.0.2'_

Gradle info:
All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.0.2, 25.3.1. Examples include com.android.support:animated-vector-drawable:27.0.2 and com.android.support:support-media-compat:25.3.1 less... (Ctrl+F1) 
There are some combinations of libraries, or tools and libraries, that are incompatible, or can lead to bugs. One such incompatibility is compiling with a version of the Android support libraries that is not the latest version (or in particular, a version lower than your targetSdkVersion.)

**Comment by daberni** [comment]
simply add a dependency to support-media-compat on your own for the correct version. this has nothing to do with this library but is a general support-library issue incorporating with different other dependencies

```
impementation "com.android.support:support-media-compat:27.0.2"
```
should work for you

**Comment by mrsergvit** [comment]
But I get a problem just after add this library.

Now it's fixed for my project in next way:
I get a source of library and put in my project. ( With Google dependency)
