### ISSUE TITLE
Dont read barcode

### ISSUE THREAD

**Issue by okocha2016** [dm77/barcodescanner#412]
It dont read certain barcodes. I attach an example
![1](https://user-images.githubusercontent.com/22304519/36692589-4bb8d640-1b17-11e8-9af6-28db095541ed.JPG)
.

**Comment by virmundi** [comment]
What format is that in? Is it one of the supported format?

BarcodeFormat.UPC_A
BarcodeFormat.UPC_E
BarcodeFormat.EAN_13
BarcodeFormat.EAN_8
BarcodeFormat.RSS_14
BarcodeFormat.CODE_39
BarcodeFormat.CODE_93
BarcodeFormat.CODE_128
BarcodeFormat.ITF
BarcodeFormat.CODABAR
BarcodeFormat.QR_CODE
BarcodeFormat.DATA_MATRIX
BarcodeFormat.PDF_417

**Comment by SaltumDis** [comment]
I am having the same problem with longer codes in CODE_93. With nexus 5x.

**Comment by UksusoFF** [comment]
Any solutions for CODE_39?
