### ISSUE TITLE
An error occured while connecting to camera

### ISSUE THREAD

**Issue by RonCan** [dm77/barcodescanner#42]
I'm getting W/CameraBase﹕ An error occurred while connecting to camera when the app opens up, a black screen with the red scan line appears.
What's causing this?
I'm using Nexus 4 with Android Lollipop 5.0

**Comment by pavs23** [comment]
Make sure you have the permission to use the camera in your manifest. Also make sure that you end any other processes using the camera

**Comment by MirzaSikander** [comment]
Any luck with this? I am also getting sort of the same problem. What happens with my application is that I am able to get one barcode scanned but it does not work the second time around. 

When `StartCamera()` is executed, the logical prints out:
`An error occured while connecting to camera:0`

but it seems to be still working as the camera starts and I am able to get the callback after I scan a barcode. In the handleRequest function I try to stop the camera using `StopCamera()` but it does not seem to work and in the logcat, it prints out 
`An error occured while connecting to camera:0`

I also tried manually getting hold of the camera after the first barcode scan, but it crashes the application. Although, if I have no issue of grabbing the camera and releasing it before the activity is started.

**Comment by NameX44** [comment]
Same here. Can't scan 2 barcode. When i startCamera a second time I've got this : 

"An error occured while connecting to camera:0"

Does someone found a solution ?

Tried many things in the stopCamera() method but nothing works..

**Comment by MirzaSikander** [comment]
I sort of figured out the problem, but not the solution :(

The issue is that the camera api being used has been deprecated.

**Comment by NameX44** [comment]
So you left this library ? or you updated it ? or found another one ?

**Comment by MirzaSikander** [comment]
Yeah I switched to another one. I would recommend searching on github for
projects that have been recently updated or contributed to.

**Comment by NameX44** [comment]
could you tell me which one please ?

**Comment by bladnor** [comment]
I have exactly the same issue. I use appcompat-v7:21.0.3 library with Android Version 4.4.4. Is there already a fix for it?

**Comment by skalathingal** [comment]
Any luck on this issue ?

**Comment by BadChoice** [comment]
Not working yet?

**Comment by augonis** [comment]
I had this issue on Nexus 5 with Android 6.0. 
Turns out I had to go into android settings>applications> (app) >permissions and explicitly allow access to the camera.

Hope this is helpful for someone.

**Comment by artemcarabash** [comment]
really? Thanks @augonis for your solution, I spent about 3 hours to find that it's all about permissions!

**Comment by fairchild88** [comment]
@augonis you are right, thx

**Comment by heitorcolangelo** [comment]
In my case, I was forgetting to call **scannerView.stopCamera()** and **scannerView = null** in **onDestroy method.**

**Comment by HeesangLee** [comment]
In my case, same issue was solved after rebooting. 
Maybe other camera application didn't unlock hardware camera before. 
But It seem to be application problem If someone download and use my app at first.

Anyone know to solve this kind of camera issue by programmatic method?

**Comment by sergioc6** [comment]
@augonis you are LEGEND my friend!

**Comment by dm77** [comment]
The zxing sample now includes code that shows how you can request camera permissions.
