### ISSUE TITLE
Barcode not read on Samsung galaxy Tab A 

### ISSUE THREAD

**Issue by rino-a** [dm77/barcodescanner#421]
Scanning is not working on Samsung galaxy Tab A with Android version 5.1.1. On other phones its working fine.

**Comment by Ramkesh9** [comment]
Same issue is with my samsung j2

**Comment by georgious070** [comment]
Samsung j3 and Samsung j5 either. Does it depend on camera characteristics or device ?
How can we fix these issues?

**Comment by VictorAdeva** [comment]
Havving still issue with Galaxy J5 2017 SM-J530F, Android 8
