### ISSUE TITLE
Certain devices have problems with catching focus

### ISSUE THREAD

**Issue by wiewioraseb** [dm77/barcodescanner#422]
I have noticed that when using barcodescanner from dm77 some devices have problems with catching camera focus and reading barcode. I have tested it on Huawei P9 Lite (2016), Lenovo TAB2 A10-30. What I have also noticed is that on those devices when I use other sample app that utilize zxing library, camera is catching focus more often which results in more rapid barcode scanning.

Is it somehow possible to customize interval length for catching camera focus? Because barcode scanning is happening instantly after camera focus is set.

Regards.

**Comment by emanuelthedude** [comment]
I have the same problem on multiple devices. At least Nexus 5, Nexus 5x. It takes a long time until the auto focus comes in. Once the focus is there the barcode scan works nearly instantly.
