### ISSUE TITLE
Unable to generate AAR of zxing library

### ISSUE THREAD

**Issue by softourS** [dm77/barcodescanner#427]
#### We've just downloaded this in order to add zxing to our app for barcode scanning purposes, but when trying assembleRelease in order to obtain the AAR file of this library, we get this message:

FAILURE: Build failed with an exception.

  What went wrong:
Could not resolve all files for configuration ':zxing:lintClassPath'.
  Could not find com.android.tools.lint:lint-gradle:26.1.2.
  Searched in the following locations:
      file:/Users/macbookpro/Library/Developer/Xamarin/android-sdk-macosx/extras/m2repository/com/android/tools/lint/lint-gradle/26.1.2/lint-gradle-26.1.2.pom
      file:/Users/macbookpro/Library/Developer/Xamarin/android-sdk-macosx/extras/m2repository/com/android/tools/lint/lint-gradle/26.1.2/lint-gradle-26.1.2.jar
      file:/Users/macbookpro/Library/Developer/Xamarin/android-sdk-macosx/extras/google/m2repository/com/android/tools/lint/lint-gradle/26.1.2/lint-gradle-26.1.2.pom
      file:/Users/macbookpro/Library/Developer/Xamarin/android-sdk-macosx/extras/google/m2repository/com/android/tools/lint/lint-gradle/26.1.2/lint-gradle-26.1.2.jar
      file:/Users/macbookpro/Library/Developer/Xamarin/android-sdk-macosx/extras/android/m2repository/com/android/tools/lint/lint-gradle/26.1.2/lint-gradle-26.1.2.pom
      file:/Users/macbookpro/Library/Developer/Xamarin/android-sdk-macosx/extras/android/m2repository/com/android/tools/lint/lint-gradle/26.1.2/lint-gradle-26.1.2.jar
      https://repo.maven.apache.org/maven2/com/android/tools/lint/lint-gradle/26.1.2/lint-gradle-26.1.2.pom
      https://repo.maven.apache.org/maven2/com/android/tools/lint/lint-gradle/26.1.2/lint-gradle-26.1.2.jar
      https://oss.sonatype.org/content/groups/public/com/android/tools/lint/lint-gradle/26.1.2/lint-gradle-26.1.2.pom
      https://oss.sonatype.org/content/groups/public/com/android/tools/lint/lint-gradle/26.1.2/lint-gradle-26.1.2.jar
  Required by:
      project :zxing

  Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

  Get more help at https://help.gradle.org

BUILD FAILED in 25s

#### We need this operative, ASAP. Please and thank you for your time and help.

**Comment by Ramkesh9** [comment]
Hi softourS , i am getting issue , please help me of you solved this .

**Comment by softourS** [comment]
Sorry, Ramkesh9. Didn't use the component in the end.
Take a look at this video, it's not integrated barcode reader, but it's what we sticked to:
https://www.youtube.com/watch?v=Tb7gmrm6z7U

**Comment by Ramkesh9** [comment]
Thanx softour,
I will opt your method very soon.

**Comment by softourS** [comment]
You're welcome, good luck with that

**Comment by Ramkesh9** [comment]
Yeah sure, actually i sloved it with some depndencies and gradle changes
but dont know how. ha ha . But My project is compiling now prefectly.

**Comment by softourS** [comment]
Glad to hear that 😄

**Comment by Ramkesh9** [comment]
Oh thanx 😊
