### ISSUE TITLE
Not Working In Android Studio 3.1.2 AppCompat version 27.1.1

### ISSUE THREAD

**Issue by akanshSirohi** [dm77/barcodescanner#431]
When implimenting this project into new project build using Android Studio 3.1.2 which uses appCompat version 27.1.1, it gives an error that shows this message below...

> All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 27.1.1, 25.3.1. Examples include com.android.support:animated-vector-drawable:27.1.1 and com.android.support:support-media-compat:25.3.1 less... (Ctrl+F1) 
> There are some combinations of libraries, or tools and libraries, that are incompatible, or can lead to bugs. One such incompatibility is compiling with a version of the Android support libraries that is not the latest version (or in particular, a version lower than your targetSdkVersion).

Please Fix It...

Here Is My Code Of build.gradle

```
dependencies {
   .....
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'me.dm7.barcodescanner:zxing:1.9.8'
    .....
}
```

**Comment by wvisible** [comment]
you can use exclude,like below
```
implementation ("me.dm7.barcodescanner:zxing:1.9.8"){
        exclude module: 'support-v4'
    }
```

**Comment by akanshSirohi** [comment]
Thanks For Reply! But I Found Another Way To Do It.
I Make My Own Project With The Help Of Your Project Source Code And Now It Is Working Fine For Me...

**Comment by arpitjindal97** [comment]
My **build.gradle** looks like this, no issue at all:

```
dependencies {
    implementation 'me.dm7.barcodescanner:zxing:1.9.8'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation"org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:support-v4:27.1.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
```

**Comment by Jenus** [comment]
Hi,  could you use dependencies version according to rootProject setting (Currently using ext configuration) if not only works on the version of specific version, for example, [support_lib   : "25.3.1"],
thus ignore the conflict of the user application configuration when using latest version support lib. 
Thanks
