### ISSUE TITLE
stopCamera() not working.

### ISSUE THREAD

**Issue by barathramakrishnan** [dm77/barcodescanner#438]
After scanning the barcode, the result is supposed to be displayed as a toast and the camera should close. But, the camera stays open with the barcode image frozen on the screen. What can be the error?

      public void scan(){
    zXingScannerView =new ZXingScannerView(getApplicationContext());
    setContentView(zXingScannerView);
    zXingScannerView.setResultHandler(this);
    zXingScannerView.startCamera();
}

@Override
public void handleResult(Result result){

    Toast.makeText(this, result.getText(), Toast.LENGTH_SHORT).show();
    zXingScannerView.stopCamera();

}

@Override
protected void onPause() {
    super.onPause();

    zXingScannerView.stopCamera();
}

**Comment by WatsonPrimera** [comment]
Alguien encontro alguna solucion a este ciclo de vida, tengo el mismo problema..   PLEASE! HELP ME..

**Comment by theking200794** [comment]
Can anyone help how can i stop camera i am facing same issue
