### ISSUE TITLE
Add support for FOCUS_MODE_CONTINUOUS_PICTURE

### ISSUE THREAD

**Issue by TeunVR** [dm77/barcodescanner#444]
Instead of manually calling autofocus every 1000ms, use FOCUS_MODE_CONTINUOUS_PICTURE to let the camera handle it.
In this case, no calls to mCameraWrapper.mCamera.autoFocus should be made, because that will stop the continuous autofocus temporarily.
Not all phones support this feature. Fallback to manually refocus if continuous is not supported.

I subclassed ZXingScannerView to support this, but it is just a quick hack. Better to support it in the core.

```
class ZXingAutofocusScannerView(context: Context) : ZXingScannerView(context) {
    private val TAG = ZXingAutofocusScannerView::class.qualifiedName

    private var fallbackFocus = false

    override fun setupCameraPreview(cameraWrapper: CameraWrapper?) {
        cameraWrapper?.mCamera?.parameters?.let{parameters->
            try {
                parameters.focusMode = Camera.Parameters.FOCUS_MODE_CONTINUOUS_PICTURE
                cameraWrapper.mCamera.parameters = parameters
            }catch(ex:Exception){
                Log.e(TAG, "Failed to set CONTINOUS_PICTURE", ex)
                fallbackFocus = true
            }
        }
        super.setupCameraPreview(cameraWrapper)
    }

    //Fall back to result of above. Ignore param, we need autofocus.
    override fun setAutoFocus(state: Boolean) {
        super.setAutoFocus(fallbackFocus)
    }
}
```

**Comment by hksfho** [comment]
this is manually focus?

would you please implement a  manually focus by touch screen? thanks

**Comment by abolfazlkalamati** [comment]
thanks

**Comment by abolfazlkalamati** [comment]
see this link : 
https://stackoverflow.com/questions/54003150/how-to-improve-the-focus-speed-of-camera/54004787#54004787
