### ISSUE TITLE
Error when use androidx

### ISSUE THREAD

**Issue by nguyenvanquan7826** [dm77/barcodescanner#447]
Hi, I use androidx, so when I add this lib, it error. Please tell me how to fix it. This error below:

Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy
Message{kind=ERROR, text=Program type already present: android.support.v4.app.INotificationSideChannel$Stub$Proxy, sources=[Unknown source file], tool name=Optional.of(D8)}

**Comment by saculbr** [comment]
Use Jetifier to force barcodescanner to use androidx

see: https://stackoverflow.com/a/52002285

**Comment by nguyenvanquan7826** [comment]
Ok, thank you
