### ISSUE TITLE
Not Camera open

### ISSUE THREAD

**Issue by DeevD** [dm77/barcodescanner#457]
10-29 13:57:32.766 433-3479/? E/QCameraStateMachine: int32_t qcamera::QCameraStateMachine::procEvtPreviewStoppedState(qcamera::qcamera_sm_evt_enum_t, void*): Error!! cannot handle evt(27) in state(0)

**Comment by abolfazlkalamati** [comment]
when open Camera in Android 6 or highr you must get Runtime Permission .
see this Link :
[](https://developer.android.com/distribute/best-practices/develop/runtime-permissions)
