### ISSUE TITLE
Barcode scanner and firestore plugin causing issue. One works, but when add other plugin it crashes.

### ISSUE THREAD

**Issue by jafsparrow** [dm77/barcodescanner#461]
Barcode scanner and firestore plugin causing issue. One works, but when add other plugin it crashes.

Plugin Firestore is working on its own and Barcode scanner is also working. But when I install firestore it shows the following error. Also tested the other way around. First firestore(worked fine) then barcode scanner (broke the whole build).

>
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.2.5+1\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
D8: Program type already present: android.arch.core.util.Function
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.

>  com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\4.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\5.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\6.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\7.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\8.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\9.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\10.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\11.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\12.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\17.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\18.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\19.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\20.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\21.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\22.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\23.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\24.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\25.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\26.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\27.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\28.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\29.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\30.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\32.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\33.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\34.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\35.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\36.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\37.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\38.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\39.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\40.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\41.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\42.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\43.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\44.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\45.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\46.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\47.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\48.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\49.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\50.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\51.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\52.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\53.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\54.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\55.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\56.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\57.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\58.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\59.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\60.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\61.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\62.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\63.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\64.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\65.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\66.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\67.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\68.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\69.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\70.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\71.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\72.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\73.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\74.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\75.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\76.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\77.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\78.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\79.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\80.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\81.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\82.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\83.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\84.jar, F:\FlutterProjects\shopV2\build\app\intermediates\transforms\dexBuilder\debug\85.jar
>   Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
>   Program type already present: android.arch.core.util.Function
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> BUILD FAILED in 50s
> Gradle task assembleDebug failed with exit code 1

**Comment by dm77** [comment]
Seems like you are using Flutter. At the moment there are no plans to support Flutter related issues. Sorry about that and good luck.
