### ISSUE TITLE
Scanner is able to scan screenshot of a QR Code. How to restrict it only for web pages ?

### ISSUE THREAD

**Issue by AndroidDeveloperGit** [dm77/barcodescanner#463]
Hello all, 

We are building an Android application whereby we have to scan a QR Code on our website. This module is working fine, but when we take a screenshot and scan that image, then also the QR code is getting scanned successfully. How do I restrict it only for web pages ? We do not want the screenshots to be scanned. Any suggestions would be helpful. 

Thanks.

**Comment by dm77** [comment]
This is not in the scope of this project. Stackoverflow might be a better place for discussion like this.
