### ISSUE TITLE
What about Targetting API 26 or more.

### ISSUE THREAD

**Issue by deathstroke007** [dm77/barcodescanner#465]
When will the new release of this library be available to update the targetSDK 26 or more. As Google stated, all 3rd party SDK needs to set targetSDK 26 or more. 

I am not able to upload the apk to the Playstore and its in production. 
Please respond ASAP.

**Comment by ArjunAchatz** [comment]
Well thats terrifying if correct ^ ... I thought only your app needed to target highest api - 1 as the build target ?

**Comment by ArjunAchatz** [comment]
Quoted - Make sure that your third-party SDK dependencies **_support_** API 26: Some SDK providers publish it in their manifest; others will require additional investigation. If you use an SDK that doesn't support API 26, please make it a priority to work with the SDK provider to resolve the issue.

**Comment by ArjunAchatz** [comment]
https://www.reddit.com/r/androiddev/comments/8wxuci/questions_about_3rd_party_libraries_targeting_api/e1zkbx4/?context=8&depth=9

https://stackoverflow.com/questions/51187530/dependencies-in-the-app-to-fulfil-the-api-target-26-in-aug-nov-2018

**Comment by ArjunAchatz** [comment]
Looks like we are okay here .. not sure what your issue is.

**Comment by azwar** [comment]
I also have same issue. I hope this library will be updated soon.

**Comment by deathstroke007** [comment]
My App Target SDK is 26 and the library's TargetSDk is 25. I am curious to know that will it be the reason Google is not able to Verify my Application. The Clear msg was - 

Your app needs to be using runtime permissions for us to complete the review. Please update your app to target API level 26 or above and resubmit the declaration form.

I am asking, do I need to update the TargetSDK of every dependency I am using or just the one which is contributing to my Android Manifest. 

There are certain dependencies in the merged Manifest which are under Manifest Sources and some are under Other Manifest File(not contributing any element to the main Manifest File).

**Comment by dm77** [comment]
Update target SDK to 28 in v1.9.13
