### ISSUE TITLE
How to scan barcode from picture?

### ISSUE THREAD

**Issue by AsusZenfoneiran** [dm77/barcodescanner#471]
How can I scan the barcode from the image please reply so much need it

**Comment by hiteshsarsava** [comment]
/**
     * Scan QR code from bitmap
     * you can convert image to bitmap and assign this function to scan
     */
    public static String scanQRImage(Uri path) {

        InputStream is;
        try {
            is = new BufferedInputStream(MyApplication.getInstance().getContentResolver().openInputStream(path));
            Bitmap bitmap = BitmapFactory.decodeStream(is);
            return scanQRImage(bitmap);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
            return "";
        }
    }

============================================================================

/**
     * Scan QR code from bitmap
     * you can convert image to bitmap and assign this function to scan
     */
    public static String scanQRImage(Bitmap bMap) {
        String contents = null;

        if (bMap.getHeight() > 500 && bMap.getWidth() > 500)
            bMap = Bitmap.createScaledBitmap(bMap, bMap.getWidth() - 300, bMap.getHeight() - 300, false);

        int[] intArray = new int[bMap.getWidth() * bMap.getHeight()];

        //copy pixel data from the Bitmap into the 'intArray' array
        bMap.getPixels(intArray, 0, bMap.getWidth(), 0, 0, bMap.getWidth(), bMap.getHeight());

        LuminanceSource source = new RGBLuminanceSource(bMap.getWidth(), bMap.getHeight(), intArray);
        BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));

        Reader reader = new MultiFormatReader();
        Map<DecodeHintType, Object> tmpHintsMap = new EnumMap<>(
                DecodeHintType.class);
        tmpHintsMap.put(DecodeHintType.TRY_HARDER, Boolean.TRUE);
        tmpHintsMap.put(DecodeHintType.POSSIBLE_FORMATS,
                EnumSet.allOf(BarcodeFormat.class));
        tmpHintsMap.put(DecodeHintType.PURE_BARCODE, Boolean.TRUE);
        try {
            Result result = reader.decode(bitmap, tmpHintsMap);
            contents = result.getText();
        } catch (Exception e) {
            Log.e("QrTest", "Error decoding barcode", e);
        }
        return contents;
    }

**Comment by suryabhairaj** [comment]
this code is not working in my case.
![nisha_code_scanner2](https://user-images.githubusercontent.com/31375031/80300307-1341cb80-87b9-11ea-83ca-ffeeefe6eb6f.png)
 
although the image get scanned using application. 
but this function does not give positive result for the same image how to handle that .
i have attached the QR code image i am taking about.

**Comment by suryabhairaj** [comment]
please respond soon it is urgent. 
-Thanks

**Comment by suryabhairaj** [comment]
Actually i have find a workaround. Please try reply early.
-Thank you for your Reply

**Comment by hiteshsarsava** [comment]
@suryabhairaj  please share your work around here. So, I can see and apply for the future projects. Thanks
