### ISSUE TITLE
getParameters failed (empty parameters)

### ISSUE THREAD

**Issue by ppking2897** [dm77/barcodescanner#476]
android.hardware.Camera.native_getParameters (Camera.java)
android.hardware.Camera.getParameters (Camera.java:1910)
me.dm7.barcodescanner.core.CameraUtils.isFlashSupported (CameraUtils.java:47)
me.dm7.barcodescanner.core.BarcodeScannerView.setFlash (BarcodeScannerView.java:251)
me.dm7.barcodescanner.core.BarcodeScannerView.setupCameraPreview (BarcodeScannerView.java:188)

Sometimes this problem will appear , my use version is 1.9.13 , is my use wrong way to set Flash?
Thanck You!!

**Comment by stephenruda** [comment]
This shows up for me when rotating my device randomly
