### ISSUE TITLE
Preview is cliped and camera preview is not roated even after changing the orientation

### ISSUE THREAD

**Issue by chaitanya-vanapamala** [dm77/barcodescanner#495]
When activity opened in portrait mode it is working fine but when we change the orientation to landscape it is clipping the bottom part as shown in below image, and also the preview orientation is not right, it is showing preview in reverse_portrait view. I have followed https://github.com/dm77/barcodescanner/blob/master/zxing-sample/src/main/java/me/dm7/barcodescanner/zxing/sample/SimpleScannerActivity.java.
**library version : 1.9.8**
Devices: I have tried Honor play, pixel all versions, Samsung tablets. I thinks it is happening in almost all devices.
![Screenshot_20190821-165145](https://user-images.githubusercontent.com/20322203/63428208-980f6500-c434-11e9-9951-f765d28a786d.png)

**Comment by abkoradiya** [comment]
in 1.9.13 also.

**Comment by abkoradiya** [comment]
> in 1.9.13 also.

Solved by removed `"orientation|screenSize"` from `android:configChanges` in manifest.
