### ISSUE TITLE
ZXingScannerView didn't work first time but working fine when app reopen after killing app

### ISSUE THREAD

**Issue by sunko8130** [dm77/barcodescanner#496]

**Comment by ParryPatel021** [comment]
This is also happening to me. When I open an Activity for the first time. It does not work, after try to kill an app, then it works fine.
Please suggest a workaround.

**Comment by Jy-Lau** [comment]
It happened at the first time the app is opened. Works fine after restarting the app/killing it. Please advice.

**Comment by smvenkateshvignesh** [comment]
Allow camera permission before entering into the screen it solves , But i'm facing green color screen in some device for first time
