### ISSUE TITLE
implementation 'me.dm7.barcodescanner:zxing:1.9.13' could not resolve while implementation 'me.dm7.barcodescanner:zxing:1.9.8' working fine

### ISSUE THREAD

**Issue by imvikasrai** [dm77/barcodescanner#499]

**Comment by petrdvorak** [comment]
@imvikasrai The 1.9.13 version is only published on JCenter, not Maven Central repository - see:

https://mvnrepository.com/artifact/me.dm7.barcodescanner/zxing?repo=jcenter

As a result, you need to add JCenter to your build files.
