### ISSUE TITLE
Flash, to be or not to be :)

### ISSUE THREAD

**Issue by PJFonseca** [dm77/barcodescanner#50]
The flash is not working on my devices, if i use:

        String flag = String.valueOf( this.getPackageManager().hasSystemFeature(PackageManager.FEATURE_CAMERA_FLASH));
        Toast.makeText(this, flag, Toast.LENGTH_LONG).show();

It gives me true, but if i use this:

        String flag = String.valueOf(mScannerView.getFlash());
        Toast.makeText(this, flag, Toast.LENGTH_LONG).show();

It gives me false, so, what can i do to activate flash?

Thanks

**Comment by designatednerd** [comment]
`getFlash` returns false until you actually turn the flash on. [Here's the relevant line as of right now](https://github.com/dm77/barcodescanner/blob/master/core/src/main/java/me/dm7/barcodescanner/core/BarcodeScannerView.java#L98).

I found a couple tricks to trying to get this to work: 

- Make sure you have the `android.permission.FLASHLIGHT` in your list of permissions.
- Make sure you call `setFlash(true)` after you've called `startCamera()`. I found if I called it before I started the camera, nothing happened on my Nexus 5.

**Comment by PJFonseca** [comment]
@designatednerd it worked. Thanks for the comment.

**Comment by EvgenyGiniApps** [comment]
I had to do it like this:
```
mScannerView.setFlash(false);
        new Handler().postDelayed(new Runnable() {
            @Override
            public void run() {
                mScannerView.setFlash(mFlash);
            }
        }, 1000);
```

**Comment by CoolMind** [comment]
@EvgenyGiniApps, delaying doesn't work, but a method of @designatednerd works if a camera preview is disabled and flash is enabled. In my case instead of `startCamera()` (because it wasn't stopped) I call `resumeCameraPreview(null)`.
