### ISSUE TITLE
Error Can't Scan QR Code

### ISSUE THREAD

**Issue by blegoh** [dm77/barcodescanner#502]
I get this error
Access denied finding property "vendor.camera.aux.packagelist"

this is my code 

import android.Manifest
import android.content.pm.PackageManager
import android.os.Bundle
import android.util.Log
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.core.app.ActivityCompat
import androidx.core.content.ContextCompat
import androidx.fragment.app.Fragment
import com.google.zxing.Result
import me.dm7.barcodescanner.zxing.ZXingScannerView

class QRFragment : Fragment(), ZXingScannerView.ResultHandler {

    private lateinit var mScannerView: ZXingScannerView

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        // Inflate the layout for this fragment
//        return inflater.inflate(R.layout.fragment_qr, container, false)
        mScannerView = ZXingScannerView(context)
        return mScannerView
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        if(context?.let { ContextCompat.checkSelfPermission(it, Manifest.permission.CAMERA) } !=
            PackageManager.PERMISSION_GRANTED){
            activity?.let {
                ActivityCompat.requestPermissions(
                    it, arrayOf(Manifest.permission.CAMERA) ,
                    50)
            }
        }
    }

    override fun onResume() {
        super.onResume()
        mScannerView.startCamera()
    }

    override fun handleResult(rawResult: Result?) {
        Log.v("AW", rawResult?.getText()); // Prints scan results
        Log.v("AW", rawResult?.getBarcodeFormat().toString());
    }

}

**Comment by vladimirVoytash** [comment]
@blegoh , Why issue was closed?
