### ISSUE TITLE
Valid QR Code not being read.

### ISSUE THREAD

**Issue by kalvish21** [dm77/barcodescanner#51]
I have a valid QR code that gets read in iOS (using a different library) but fails to be read in Android. I have followed the example verbatim and still not getting it. Please advise -- Is there anything I'm doing wrong? Perhaps in generating the QR code? But it works in iOS?

I have attached my QR code below:

![0bb5668edbb67eb](https://cloud.githubusercontent.com/assets/2179704/5913241/750ac3fa-a5ae-11e4-9205-da35539db7f4.png)

**Comment by aristide** [comment]
Hello @kalvish21 

i 've implemented @dm77  **Zbar** library and here is what i got from your QRCODE image:
```
Uv0tUft6C5L/6DUeUp7V74I4vAi1j3AZOSe2vS2pHQwb9/5881wlJa08aQHkw6qj0/m5P/xzWKsm
IQ6RJn3uCPz3tfl9GA0KaOM+awExap2PmtiVQyB0gm1fz1PEgDlP0cJh3V65jjqWWOljp6DhMfyu
EYNvFUu526pWTJIAxFQ/7vFMBgH/eFXIMnVAHg0quhDD6M8CzW9nRYZRN0N7/pMrxSScJEk8S6Ck   
GyZlnaeYMO2DNasw+ZE+lSFok0jSQVZWsZSM3/OFQyZ+fMca4WsffpQM48xSHkDN+N8OND2BD64c
1G49OKNqCU5EBM/qTbz6816oWjU+SkHouMsODg==
```
i read this [thread](http://stackoverflow.com/questions/13268250/android-zxing-vs-zbar) from Stackoverflow before deciding to use **zbar** or **zing**

**Comment by kalvish21** [comment]
Yep. Works on __ZBar__, not on __ZXing__. Not sure why.

**Comment by iv-mexx** [comment]
I'm having the same problem - It works when using **ZBar**, but not when using **ZXing**. 
It actually recognizes Barcodes correctly, only QR-Codes are not working.

I have tried the Sample Project (using the zxing simple fragment) and it works fine, but using the exact same code for the fragment in my own project fails.

I would prefer to use **ZXing** if possible because of the ResultParsers (I have a bunch of custom ResultParsers added for additional Contents)!

**Comment by kalvish21** [comment]
__ZXing__ actually works very well if you use it on small QR codes. The one I posted is very large and somehow it fails to recognize those.

**Comment by iv-mexx** [comment]
Hm, for me **ZXing** does not even work for small QR codes. 
It works on the Emulator (Genymotion) though, but on the emulator the ```mScannerView.startCamera();``` in the result handler does not start the camera anymore.

**Comment by nocheinAndi** [comment]
I've got the same QR-code problem. The scanner does not recognize small or big QR-codes.

**Comment by dm77** [comment]
Scanning the qrcode above using the zxing sample v1.7 works fine. See scan results in screenshot attached:

![2015-04-22 00 45 22](https://cloud.githubusercontent.com/assets/129133/7265417/b502a05a-e856-11e4-8acf-e421e0722bb8.png)

**Comment by kalvish21** [comment]
Doesn't make sense to close this issue. This is an issue I can replicate across 5 devices. There're plenty of others with the same issue. I think its worth looking into.

**Comment by dm77** [comment]
Sorry about that. I was unable to replicate with the sample project on 3 devices. Hence I figured it had something to with your project rather than the library. Are you able to replicate the problem with sample project on those 5 devices you mentioned?

**Comment by dm77** [comment]
Also can you test your project with version 1.7 that I released a few minutes ago? It includes some bug fixes related to the viewfinder that might resolve your issue. Let me know.

**Comment by dm77** [comment]
I tested on the following 3 devices:
1.) HTC Thunderbolt, Android 2.3 (This was the worst of the 3, took at least 5 seconds to scan the qrcode)
2.) Samsung Galaxy Nexus, Android 4.2.2
3.) Nexus 5, Andriod 5.1

**Comment by kalvish21** [comment]
It's having issues with Galaxy Note 4.
