### ISSUE TITLE
Not Scanning properly with dual or triple back camera android devices

### ISSUE THREAD

**Issue by HarshBinSem** [dm77/barcodescanner#520]
Hi , i'm using this library since a long time now , this library works fine with single back camera android devices. but this time i'm using it with triple camera device, can you please tell me if this library works with dual or triple camera devices ?

**Comment by cainy393** [comment]
I can try help if you provide some actual error logs/code so we know what the probem is.

**Comment by corigtous** [comment]
Go to your camera settings and turn on auto focus. It should scan after that

**Comment by corigtous** [comment]
It still happens
