### ISSUE TITLE
error while running app with basic implementation of Zxing

### ISSUE THREAD

**Issue by Rohan9433** [dm77/barcodescanner#523]
W/CameraBase: An error occurred while connecting to camera: 0

**Comment by cainy393** [comment]
You need to specify that you need camera access in your AndroidManifest.xml file and might also need to request camera permission in your activity class.

###AndroidManifest.xml

    <application>
        ...
        <uses-feature android:name="android.hardware.camera" />
        <uses-permission android:name="android.permission.CAMERA" />
    </applciation>

###MainActivity.java

    protected void onCreate(Bundle savedIntanceState) {
        ...
        ActivityCompat.requestPermissions(this, new String[]{CAMERA}, REQUEST_CAMERA);
    }    

See [this guide](https://www.androidtutorialonline.com/android-qr-code-scanner/) for a full example.
