### ISSUE TITLE
VERY OLD version of zbarimg in macOS

### ISSUE THREAD

**Issue by johfpardo** [dm77/barcodescanner#539]
I created a bash script to scan QR codes and I want it to be a multi-platform script to use in linux and macOS. However, the macOS's zbarimg can't read some QR codes well as linux's zbarimg does.

I searched why was the reason of this and I found that the version of zbarimg that macOS uses is lower than linux uses **(0.10 < 0.23).**

So my question is how I can upgrade the zbarimg to 0.23 version in macOS and It would work as expected? 

Please help me

**Comment by dm77** [comment]
You may want to reach out to folks at https://github.com/ZBar/ZBar/tree/master/android
