### ISSUE TITLE
Aspect ratio

### ISSUE THREAD

**Issue by Crustus** [dm77/barcodescanner#58]
Hello there,

Im using your ZBar library but i have little problem or maybe missunderstanding.
If I create xml layout where, for example, i put two LinearLayouts which have dynamic width
first
android:layout_width="0dp"
android:layout_weight="0.6"
and second
android:layout_width="0dp"
android:layout_weight="0.4"

and i put ZBarScannerView into first layout, the image show as preview is distorted, have wrong aspect ratio
How to fix it? I have tried to call requestLayout and invalidate but no help

i was checking a code a little bit, but it looks it uses only Display resolutions and not current View container?

Thx

**Comment by dm77** [comment]
@Crustus sorry for the delay. Previous versions of this library only support full screen camera vies. Version 1.7 which I just released fixes the aspect ratio issue.
