### ISSUE TITLE
how to change border size 4:3 ratio

### ISSUE THREAD

**Issue by h4h13** [dm77/barcodescanner#61]
any help thanks how to change the scanner view size

**Comment by Venzon** [comment]
My solution will be to overwrite some base classes like BarcodeScannerView
I am doing such thing in my project to change core code

**Comment by deepdoradla** [comment]
How are you overwriting the base classes? I tried to add the core classes as modules and I am getting this gradle error 
Error:(12, 0) Could not find property 'supportLibraryDependency' on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@4f0620a1.

Even I need to change the border size. Please help.

**Comment by dm77** [comment]
@h4h13 is there a mockup for what you are trying achieve? I can give you an xml layout based on your mockup.

**Comment by naorcho** [comment]
I have also got the same error:
Error:(12, 0) Could not find property 'supportLibraryDependency' on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@28b095df.

How did you solve it?
