### ISSUE TITLE
Wifi switching stops scanning

### ISSUE THREAD

**Issue by saqibateeq** [dm77/barcodescanner#63]
Scanner activity stops scanning code as WIFI goes ON from OFF state. After exact 3, 4 code scanning it doesn't scan anymore code. Until I exit application and restart camera activity.
I am checking it over LG G3

**Comment by saqibateeq** [comment]
Is there even someone who bother to read?

**Comment by saqibateeq** [comment]
Any update except closing and reopening it

**Comment by dm77** [comment]
@saqibateeq Sorry for the delay. Can you please give me instructions on how to reproduce the issue?

**Comment by saqibateeq** [comment]
First time it occurred when network switched from wifi to edge (data network). Then we tested it manually by switching wifi ON/OFF after scanning was started. Right after 3 or 4 scanning it stops scanning anymore codes. While it stays on the scanning screen with camera open. But no result or scanning code anymore.

**Comment by dm77** [comment]
Thanks for the feedback. I am sorry for the delay, I just did a bug fix release yesterday. I am still working on more enhancements and bug fixes. I will tackle this issue in the next few days. I will release a new version of the library over the weekend. Thanks for your patience.

**Comment by saqibateeq** [comment]
Thank you for responding.
