### ISSUE TITLE
Cant scan consecutively 

### ISSUE THREAD

**Issue by myion8you** [dm77/barcodescanner#66]
If I complete one scan, all subsequent tries fail to read barcode meaning user is left trying to scan barcode but it wont scan.

**Comment by saqibateeq** [comment]
I have same issue when I switch wifi from OFF state to ON and try to scan

**Comment by DasCody** [comment]
You have to call startCamera() after each scan (or at least that's how I fixed it).

Relevant code:

private ZXingScannerView mScannerView;

    @Override
    public void handleREquest(Result rawResult)
    {
        mScannerView.startCamera();
    }

**Comment by dm77** [comment]
@DasCody Oh good point, I thought it was pretty obvious from the samples, but could be what is missing from your code @myion8you. Can you please confirm?

**Comment by ReversiPro** [comment]
Thanks a lot, this works for me!

**Comment by doruchidean-lifeishard** [comment]
just calling #startCamera() was not working for me on v 1.9.8
I had to #stopCamera(); #setResultHandler(handler); #startCamera()
