### ISSUE TITLE
How to customise the scanner UI?

### ISSUE THREAD

**Issue by deepdoradla** [dm77/barcodescanner#67]
I have integrated Zxing QR scanner. 
I need to customise the scanner UI. But I am unable to understand how?
Any help will be appreciated.

**Comment by QuadFlask** [comment]
You can customize `ViewFinderView`'s `onDraw` method to drawing something in scanner UI.
It draw shade mask and view finder border

**Comment by dm77** [comment]
@deepdoradla Can you tell us a bit about how you intend to customize it? Is there a mockup that you can share?

**Comment by HugoMatilla** [comment]
Hi, @dm77 

first, thanks for the library. You did an awesome work here.

About the issue, In my case I want to add my app logo to top of the the screen, some hint text and other things.  Is there a way to pass a custom xml layout to the ZBarScannerView? Or anyway to customise the UI?

Thank you in advance.

**Comment by dm77** [comment]
@HugoMatilla thank you for the nice comment :)

You can use a layout like below in combination with a full screen theme like below:

Layout:

```
<?xml version="1.0" encoding="utf-8"?>

<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
             xmlns:tools="http://schemas.android.com/tools"
             android:orientation="vertical"
             android:layout_width="match_parent"
             android:layout_height="match_parent">
    <fragment android:name="me.dm7.barcodescanner.zxing.sample.ScannerFragment"
              android:id="@+id/scanner_fragment"
              android:layout_width="match_parent"
              android:layout_height="match_parent" />

    <ImageView
        android:src="@drawable/ic_launcher"
        android:layout_gravity="top"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"/>

    <TextView
        android:layout_gravity="center|bottom"
        android:text="Place a barcode in the viewfinder rectangle to scan it."
        android:layout_width="wrap_content"
        android:textColor="#ffffff"
        android:layout_height="wrap_content"/>
</FrameLayout>
```

Full screen theme:
```
<style name="AppFullScreenTheme" parent="@style/Theme.AppCompat.Light.NoActionBar">
    <item name="android:windowNoTitle">true</item>
    <item name="windowActionBar">false</item>
    <item name="android:windowFullscreen">true</item>
    <item name="android:windowContentOverlay">@null</item>
</style>
```

This results in something like this image:

![2015-04-22 19 52 46](https://cloud.githubusercontent.com/assets/129133/7283928/3524e374-e8f7-11e4-83a1-6d2f75b6a50e.png)

Hope that helps.

**Comment by MrLoveQD** [comment]
Hi. @dm77 
I have a UI: 
![screenshot_2015-04-23-08-38-31](https://cloud.githubusercontent.com/assets/4046835/7289475/f8317186-e99a-11e4-8c3a-9336b75e4e3b.png)

I would like to lift ViewFinderView slightly higher.
How do I do?

I opened ViewFinderView.java file but don't know edit it.

**Comment by dm77** [comment]
@MrLoveQD Firstly please make sure you are using version 1.7 of the library that I released yesterday: http://search.maven.org/#artifactdetails%7Cme.dm7.barcodescanner%7Czxing%7C1.7%7Caar

In your xml layout are you overlaying the elements on top of the Camera fragment?

Instead of overlaying elements on top of Camera fragment, you can implement a layout using LinearLayout:

LinearLayout (orientation =vertical)
-- CameraFragment (weight = 1)
-- Some view with gravity bottom

With v1.7 of the library, the camera preview will adjust its size instead of stretching and also the viewfinder adjust's its position based on the size and position of the camerapreview.

Sorry for the terse reply. Hope that helps.

**Comment by MrLoveQD** [comment]
Hi.
I'm using previous version (1week ago).
I' tested new version (1.7) and try again,but camera not full width my layout.
I reused the previous version.
And I used Overlaying the Action Bar (https://developer.android.com/training/basics/actionbar/overlaying.html).
Look it ok :D
Thanks you so much.
This library really very good.

**Comment by HugoMatilla** [comment]
@dm77 Thank you very much. Just what I needed. :)

**Comment by dm77** [comment]
@HugoMatilla you are welcome. 

@MrLoveQD Thank you very much. I couldn't understand if your problem was resolved. Are you good now? Can I close this issue?

**Comment by MrLoveQD** [comment]
@dm77 Yes. Now, Ok for me.
Thanks you :D

**Comment by dm77** [comment]
Perfect! Thank you.

**Comment by ketanpatel25** [comment]
Hi @dm77  
Your barcodescanner lib is nice 
but sum ui not configure in scanner preview 

screen Xml 

<?xml version="1.0" encoding="utf-8"?>
<FrameLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <FrameLayout
        android:layout_gravity="center"
        android:id="@+id/content_frame"
        android:layout_width="match_parent"
        android:layout_height="350dp" />

</FrameLayout>

This results in something like this image:
![device-2016-02-08-130147](https://cloud.githubusercontent.com/assets/1632757/12880267/d3149f2c-ce64-11e5-81cb-d662d4c6ba3d.png)

Please tall how to show full screen scanner preview

**Comment by chitrey** [comment]
hiiiiii @dm77 , as everyone i would also like to thank you for this wonderful library. It has helped me a lot and eased so many process soooo much. Thank you very much. I have a small issue for which i would like to seek your assistance. 
![1](https://cloud.githubusercontent.com/assets/20356418/17285309/b9da9906-57e1-11e6-8c4b-25a4a1bcbc69.png)

right now this is my ZXingScannerView. I would like to increase the width and height of that scanner preview. Also i would like to remove those border.

I want something like this:
![2](https://cloud.githubusercontent.com/assets/20356418/17285353/f464b796-57e1-11e6-97d5-0b4841742709.png)

Any help/assistance would be really appreciated. Thanks in advance :) :+1:

**Comment by Abdulwahid80** [comment]
hi dm77
first I thank you for the library
what I want is to customize the size of the Scanner to the top of portrait scene with width 300dp and 200dp height how to do that?
with my thanks

**Comment by ngengemyolwin** [comment]
@Abdulwahid80  
is there any solution on that one. I am also trying on the same function like u

**Comment by ngengemyolwin** [comment]
@dm77 
firstly , i like to thank to ur library .
I would like to check the following case .
LinearLayout (orientation =vertical)
-- CameraFragment (weight = 1)
-- Some view with gravity bottom
for the case ,If the bottom part of the view is more longer than CameraFragment, the Scanner not working properly.

I also want to check how to focus on camera view  out of the center . I want to set ViewFinderView Rectangle on the top of the screen . but focus lost in scanning QR . 

Thanks in advance.

**Comment by intanryeo** [comment]
Hello. I having a problem to make a hint below the square QR scanner. How to do that? 
![photo_2017-08-30_11-17-45](https://user-images.githubusercontent.com/30853221/29854036-153b1e4a-8d76-11e7-84a2-638109914219.jpg)

**Comment by mjalijani** [comment]
how can i set flash button ? 
i want to user can to turn on or off the flash

**Comment by it57070047** [comment]
Hii,  @dm77  
First i thank you u very very very much for Scanner lib but I've a problem !! 
I want to remove red laser. What should I do?

**Comment by DavidChuks** [comment]
Can't find me.dm7.barcodescanner.zxing.sample.ScannerFragment, unresolved

**Comment by Mathitos** [comment]
@it57070047 you can use setLaserEnabled(false)

**Comment by ITaran7237** [comment]
Hi @dm77 !! Thanks for scanner. Can you help me, how can i create custom scanner like this??
![screenshot_2](https://user-images.githubusercontent.com/29452864/47395554-db734700-d72f-11e8-9d70-c0bac4af0ad2.png)

**Comment by neonwarge04** [comment]
I am really bothered by these green corners and blinking red bar. Is there a way to remove it? Is it that really necessary?

**Comment by saipriya-ar** [comment]
I just want the four corner lines and the camera ,I don’t want the grey background.
Thanks in advance
