### ISSUE TITLE
Setting up project

### ISSUE THREAD

**Issue by kalvish21** [dm77/barcodescanner#70]
I'm trying to update the code on here, not able to get the project setup locally on Android Studio. Gradle keeps complaining about various settings. Does anybody have instructions on how they were able to do it?

**Comment by kalvish21** [comment]
Just want to know how they got the project to be setup locally and compile.

**Comment by dm77** [comment]
Please take a look at the complete samples for zbar and zxing:

https://github.com/dm77/barcodescanner/tree/master/zbar/sample
https://github.com/dm77/barcodescanner/tree/master/zxing/sample
