### ISSUE TITLE
Gradle sync issue

### ISSUE THREAD

**Issue by deepdoradla** [dm77/barcodescanner#71]
I have added the core and Zxing as modules to my project in AndroidStudio. During the sync it gives me this error.
Error:(12, 0) Could not find property 'supportLibraryDependency' on org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler_Decorated@62a617a8.

Is this a bug or I am missing something?

**Comment by dm77** [comment]
Based on the other issues you opened, I am assuming this one is now resolved for you. Please reopen if I am incorrect.
