### ISSUE TITLE
EAN13 is read as ISBN10 in ZBar

### ISSUE THREAD

**Issue by JerabekJakub** [dm77/barcodescanner#73]
Hi,
I'm using **ZBar** library (latest version 1.6.3) and when I'm scanning EAN13 9788074477768, it returns me 8074477762 as ISBN10. With another EAN13 9006900014292 it works fine.

When I switched from ZBar to ZXing, scanning '9788074477768' was OK.

Problematic EAN13:
![ean13](https://cloud.githubusercontent.com/assets/6553750/7131946/e9315fce-e284-11e4-8f77-11ec73f52597.png)

**Comment by dm77** [comment]
@JerabekJakub Unfortunately this library doesn't do the actual job of parsing the barcodes. Please submit a request here: http://sourceforge.net/p/zbar/news/
