### ISSUE TITLE
how use front camera

### ISSUE THREAD

**Issue by mmuttaqin** [dm77/barcodescanner#75]
is there any config, so we can use front camera?
We use Nexus 7 there are not back camera

**Comment by dm77** [comment]
Added support for front-facing camera in v1.7. Please use the startCamera(int cameraId) method. Thank you.

**Comment by zieru** [comment]
Hello,

can you tell me, how to use the front camera.
Because I don't know how to figure it out,

I use this, but it give me only black
`mScannerView.startCamera(1);`
