### ISSUE TITLE
How to get image bitmap after scan

### ISSUE THREAD

**Issue by MrLoveQD** [dm77/barcodescanner#76]
Hi.
After scan qrcode from camera, i want store that qrcode image to sdcard (or to display to an other image -  same as Zxing app).
In handleResult(Result rawResult) function, I tried rawResult.getRawBytes(); to convert to a bitmap,but rawResult.getRawBytes() return null.
Please help me.
Thanks.

(sorry for my English)

**Comment by dm77** [comment]
Hmm interesting. I will update the handleResult method to get a copy of the bytes as well. It will be in the next version of the library, probably in the next couple of days. 

If you want something urgently, you can try extending ZXingScannerView:

```
public class MyZXingScannerView extends ZXingScannerView {
    private byte[] imageData;
    @Override
    public void onPreviewFrame(byte[] data, Camera camera) {
        this.imageData = data;
        super(data, camera);
    }

    public void handleResult(RawResult result) {
        // Use this.imageData here.
     }
}

**Comment by MrLoveQD** [comment]
yeah. Thanks you so much.
It's very usefull.

Please help me:
https://github.com/dm77/barcodescanner/issues/67
