### ISSUE TITLE
Mirror effect on front camera.

### ISSUE THREAD

**Issue by hello-sirius** [dm77/barcodescanner#77]
Barcode on front camera is not read. Zxing scanner can't find Barcode because it Mirrored.

**Comment by dm77** [comment]
@hello-sirius Thanks for reporting the issue. I also noticed that front facing camera was mirrored, but found that the default camera app also does this. I didn't have any issues testing qrcodes or barcodes with front facing camera on my devices. Can you provide a sample barcode that didn't work for you?

**Comment by hello-sirius** [comment]
I'm sorry it's my fault. After reading your reply I understand what went wrong. I chose not readable barcode. On the main camera all read (8Mp). Then the front camera (2Mp) image was slightly blurred and lines merged. When I took the barcode bigger all was well.

Thank you for the excellent library !!! And I'm sorry for disturbing.

P.S. Nexus 4 Lolipop 5.0.2

**Comment by dm77** [comment]
@hello-sirius no worries at all. Thank you :)
