### ISSUE TITLE
UnsatisfiedLinkError on variety of phones

### ISSUE THREAD

**Issue by grennis** [dm77/barcodescanner#78]
Using version 1.6.3 and I'm getting crash reports from a few percentage of users. The crash is happening in static constructor of ImageScanner (stack trace below). 

Only happens on Android 4.2.2, 4.1.2, and 4.0.4.

Phones: Commonly Samsung SGH T399, T999, SPH D710; Amazon SD4930UR; LG E970, LS970, P930, and a variety of others.

java.lang.UnsatisfiedLinkError: Cannot load library: soinfo_link_image(linker.cpp:1652): could not load library "libiconv.so" needed by "libzbarjni.so"; caused by load_library(linker.cpp:759): library "libiconv.so" not found
       at java.lang.Runtime.loadLibrary(Runtime.java:372)
       at java.lang.System.loadLibrary(System.java:514)
       at net.sourceforge.zbar.ImageScanner.()

**Comment by dm77** [comment]
Sorry about the error and thanks for reporting. For version 1.7, I merged in this commit: https://github.com/dm77/barcodescanner/commit/bc5ae5afe967de8fa867ddfa33030df9fdd579c6, may be that resolves the issue?

**Comment by grennis** [comment]
Thanks. I will give it a try. For now we have disabled barcode scanning in version 4.2 and earlier so it's not urgent. 4.2 and older is < 5% of the market these days.

**Comment by dm77** [comment]
Thank you so much @grennis.
