### ISSUE TITLE
Screen proportion is not accurate for Simple zxing sample on galaxy 4

### ISSUE THREAD

**Issue by vors** [dm77/barcodescanner#8]
Repro:
1) Create sample app from README.md
2) Install it on Galaxy 4
3) Run application
expected:
Screen proportion is same as regular camera app
actual:
Screen stretched in X direction. Check screenshots for references.

![screenshot_2014-04-04-00-51-26](https://cloud.githubusercontent.com/assets/816680/2613005/e11f10fc-bbce-11e3-9e16-5b533f1d9a7a.png)

![screenshot_2014-04-04-00-51-00](https://cloud.githubusercontent.com/assets/816680/2613007/e54acde2-bbce-11e3-98c6-3f6079f681d2.png)

**Comment by dm77** [comment]
@vors Very sorry for delay. The fix from #10 has been merged in and a new version 1.7 has been released. If you are on an older version @willemstoker's answer above is correct. Thank you.
