### ISSUE TITLE
start camera without decoding qrcode

### ISSUE THREAD

**Issue by tlemansec** [dm77/barcodescanner#82]
Is it possible to start the camera without looking for the qrcode, and to wait for a button to be pressed to look for that qrcode?

thanks

**Comment by dm77** [comment]
@tlemansec The camera only starts when you call mScannerView.startCamera();  For example in this sample: https://github.com/dm77/barcodescanner/blob/master/zxing/sample/src/main/java/me/dm7/barcodescanner/zxing/sample/ScannerFragment.java#L175, notice how the camera is re-started after the user presses positive button in the dialog. 

You could use similar logic in your app.
