### ISSUE TITLE
Result (getContents()) String Encoding ZBAR

### ISSUE THREAD

**Issue by LFE01** [dm77/barcodescanner#83]
Hi, I just figured out, that the string result probably contains SJIS (SHIFT_JIS) encoded character. Just try to scan a QR code with german "Umlaute" such as "Ä Ö Ü' or latin expressions such as "è ò ù" and so on. 

The result handler always encode these expressions as SJIS and the other as UTF-8 characters.

Do you have any information about this issue? Or how to avoid that behavior?
Any help/info would be greatly appreciated.

LFE

**Comment by dm77** [comment]
Hi @LFE01 This is the first I am hearing about this issue. I will look into it more and get back to you. Sorry for  the delay :(

**Comment by LFE01** [comment]
No problem @dm77.
You can reproduce the failure by the following string:

“ÄTest 1“

If the expression is standalone 
"Ä Test 1" the encoding works like a charm.

I'm looking forward to hear from you.
Thanks for your efforts and for the nice library!

**Comment by LFE01** [comment]
Just figured out that it just happens with the ZBar library. ZXing will work. Maybe I'll find some information about setting "Hints" for string encoding like in ZXing.

**Comment by LFE01** [comment]
Ok after I found a solution, for the same problem, written in Objective-C, I've just adapted the follwing Objective-C Code to Java:

Objective-C
 NSString* barcode = symbol.data;
    if ([barcode canBeConvertedToEncoding:NSShiftJISStringEncoding])
    {
        barcode = [NSString stringWithCString:[barcode cStringUsingEncoding: NSShiftJISStringEncoding] encoding:NSUTF8StringEncoding];
    }

Java:
new String(newResult.getContents().getBytes("SHIFT-JIS"), "UTF-8")

Regards,
LFE01

**Comment by dm77** [comment]
So sorry for the delay. I am glad you figured it out :)

**Comment by torstenlehmann** [comment]
@LFE01 

> Java:
> `new String(newResult.getContents().getBytes("SHIFT-JIS"), "UTF-8")`

Thanks. That saved my evening.

Tried "ISO-8859-1" but "SHIFT-JIS" solved it. 

Should be included in the documentation as a workaround at least.

@dm77 Thanks for this library.
