### ISSUE TITLE
1.7.1 : Zbar example basic : autofocus failed

### ISSUE THREAD

**Issue by Paul75** [dm77/barcodescanner#85]
Hello,

In the last version (before it works). When I do a simple activity like a exemple in the home page of your project I have a error :

java.lang.RuntimeException: autoFocus failed
            at android.hardware.Camera.native_autoFocus(Native Method)
            at android.hardware.Camera.autoFocus(Camera.java:1299)
            at me.dm7.barcodescanner.core.CameraPreview$1.run(CameraPreview.java:245)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:211)
            at android.app.ActivityThread.main(ActivityThread.java:5317)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

Thanks

**Comment by dm77** [comment]
Hi @Paul75 can you tell me which version you are using? Thank you.

**Comment by Paul75** [comment]
I use the last 1.7.1

**Comment by dm77** [comment]
Thanks for the quick reply. I didn't see any issues running the sample app on my end. But I will take a look now.

**Comment by dm77** [comment]
@Paul75 Can you try installing this sample apk file: https://www.dropbox.com/s/5688oi0ekn4egcs/sample-debug.apk?dl=0 and see if you can reproduce the issue. Also can you tell me which device you are using?

**Comment by Paul75** [comment]
It also do a bug.

I gave a Xperia Z1.
Le 20 mai 2015 23:01, "Dushyanth Maguluru" <notifications@github.com> a
écrit :

**Comment by dm77** [comment]
Have to see if this will help: http://www.hitziger.net/blog/android-camera-autofocus-failed/

**Comment by Paul75** [comment]
I don't understand What I must change …..

2015-05-20 23:13 GMT+02:00 Dushyanth Maguluru <notifications@github.com>:

> Have to see if this will help:
> http://www.hitziger.net/blog/android-camera-autofocus-failed/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dm77/barcodescanner/issues/85#issuecomment-104040844>.
>



-- 
Paul

**Comment by sainttail** [comment]
I also got this crash
using the app download from here https://www.dropbox.com/s/5688oi0ekn4egcs/sample-debug.apk?dl=0

I use galaxy s2 with custom cyanogenmod rom 12, Android 5.1.1

**Comment by dm77** [comment]
@Paul75 sorry about the delay in responding. I will have to release a new version of the library with a fix for the xperia devices. See @plastiv comment here: https://github.com/dm77/barcodescanner/issues/7#issuecomment-105019851

**Comment by dm77** [comment]
@Paul75 @sainttail  could one of you be able to test this sample Zxing APK file: https://www.dropbox.com/s/ttl5g97tpykexdb/zxing-sample.apk?dl=0

I made a change to catch Runtime autofocus failed exception and retry again. But I don't have a Sony device to test myself :(. So can one of you please test the above APK on your device and let me know if there are any issues? Thank you so much for your time.

**Comment by Paul75** [comment]
Hello,

I test your version and it same bug. nothing change.

Thanks

**Comment by dm77** [comment]
Thank you so much for testing it so quick. I will continue looking for a fix.

**Comment by markus-woerz** [comment]
I have the same crash on my Xperia Z3 Compact. Also for the latest APK.
I am also ready to test new fixes.

**Comment by dm77** [comment]
@markus-woerz Thank you so for much testing. Do you have happen to have the stack track handy?

**Comment by markus-woerz** [comment]
I click SIMPLE ACTIVITY SAMPLE and then I get:

    05-28 10:33:46.959  16161-16161/me.dm7.barcodescanner.zxing.sample E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: me.dm7.barcodescanner.zxing.sample, PID: 16161
    java.lang.RuntimeException: autoFocus failed
            at android.hardware.Camera.native_autoFocus(Native Method)
            at android.hardware.Camera.autoFocus(Camera.java:1299)
            at me.dm7.barcodescanner.core.CameraPreview$1.run(CameraPreview.java:251)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:211)
            at android.app.ActivityThread.main(ActivityThread.java:5321)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by markus-woerz** [comment]
By the way: For now I use a hack I found somewhere on the internet to delay the crash. This seems to work until I restart the activity, so it's not a real solution.

    public class MyBarcodeScannerView extends ZXingScannerView {
        public MyBarcodeScannerView(Context context) {
            super(context);
        }

        public MyBarcodeScannerView(Context context, AttributeSet attributeSet) {
            super(context, attributeSet);
        }

        @Override
        public void startCamera() {
            setAutoFocus(false);
            super.startCamera();
            setAutoFocus(false);
        }

        @Override
        public void onPreviewFrame(byte[] data, Camera camera) {
            super.onPreviewFrame(data, camera);
            setAutoFocus(true);
        }
    }

**Comment by dm77** [comment]
@markus-woerz Ah hmm interesting. Seems like that code you are using is making sure the camera is ready before setting autofocus.

Also thank you for the backtrace. Seems like I will have to catch another runtime exception around line 251. I made that change and here is another APK file with this new fix.

If you don't mind can you test the APK on your device when you get a chance and let me know if it resolves the crash? https://www.dropbox.com/s/yj5xjvo15j5vv4t/zxing-sample-v2.apk?dl=0

**Comment by Paul75** [comment]
I test and same bug ....

2015-05-28 10:49 GMT+02:00 Dushyanth Maguluru <notifications@github.com>:

> @markus-woerz <https://github.com/markus-woerz> Ah hmm interesting. Seems
> like that code you are using is making sure the camera is ready before
> setting autofocus.
>
> Also thank you for the backtrace. Seems like I will have to catch another
> runtime exception around line 251. I made that change and here is another
> APK file with this new fix.
>
> If you don't mind can you test the APK on your device when you get a
> chance and let me know if it resolves the crash?
> https://www.dropbox.com/s/yj5xjvo15j5vv4t/zxing-sample-v2.apk?dl=0
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dm77/barcodescanner/issues/85#issuecomment-106236041>.
>



-- 
Paul

**Comment by dm77** [comment]
Thanks @Paul75 . According to @plastiv there was one other place where I autoFocus error could occur. So I made one more change and I think I finally covered all 3 calls to mCamera.autoFocus with try/catch. See my commit here: https://github.com/dm77/barcodescanner/commit/c8ec26066c5a6aead9b68cf2ad3684821de5b1a5

And here is a sample APK file: https://www.dropbox.com/s/b4qcwdpkczss9ru/zxing-sample-v3.apk?dl=0

If yourself or @markus-woerz can test once again (please) that would be great. Thank you so much.

**Comment by Paul75** [comment]
It works...

2015-05-28 11:05 GMT+02:00 Dushyanth Maguluru <notifications@github.com>:

> Thanks @Paul75 <https://github.com/Paul75> . According to @plastiv
> <https://github.com/plastiv> there was one other place where I autoFocus
> error could occur. So I made one more change and I think I finally covered
> all 3 calls to mCamera.autoFocus with try/catch. See my commit here:
> c8ec260
> <https://github.com/dm77/barcodescanner/commit/c8ec26066c5a6aead9b68cf2ad3684821de5b1a5>
>
> And here is a sample APK file:
> https://www.dropbox.com/s/b4qcwdpkczss9ru/zxing-sample-v3.apk?dl=0
>
> If yourself or @markus-woerz <https://github.com/markus-woerz> can test
> once again (please) that would be great. Thank you so much.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dm77/barcodescanner/issues/85#issuecomment-106241315>.
>



-- 
Paul

**Comment by dm77** [comment]
Finally. Thank you so much for testing again. I will release version 1.7.2 with this fix.

**Comment by markus-woerz** [comment]
@Paul75 @dm77 works here as well :) Thank you so much!

**Comment by dm77** [comment]
Thank you @markus-woerz  :)

**Comment by Paul75** [comment]
I have a question it is normal that in my Sony it not take all the screen ???

**Comment by dm77** [comment]
@Paul75 The samples currently are not using the fullscreen them. If you use the fullscreen theme and overlay actionbar and overlay elements it should take up all the screen. 

Alternative is to stretch the camera preview which then causes issue #8.

If you need help with overlay elements see my comment in #67

**Comment by Paul75** [comment]
no I tell that it not take all in right and left ....

2015-05-28 11:28 GMT+02:00 Dushyanth Maguluru <notifications@github.com>:

> @Paul75 <https://github.com/Paul75> The samples currently are not using
> the fullscreen them. If you use the fullscreen theme and overlay actionbar
> and overlay elements it should take up all the screen.
>
> Alternative is to stretch the camera preview which then causes issue #8
> <https://github.com/dm77/barcodescanner/issues/8>.
>
> If you need help with overlay elements see my comment in #67
> <https://github.com/dm77/barcodescanner/issues/67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dm77/barcodescanner/issues/85#issuecomment-106246506>.
>



-- 
Paul

**Comment by dm77** [comment]
Hi @Paul75 . Sorry if I misunderstood. I think your issue is similar to this: https://github.com/dm77/barcodescanner/issues/87. Am I wrong? 

If it is the same, then the fix is to use a full screen theme, and any other view elements need to be overlaid on top of the camera preview.

**Comment by Paul75** [comment]
it same that #87 yes ...

2015-05-28 11:35 GMT+02:00 Dushyanth Maguluru <notifications@github.com>:

> Hi @Paul75 <https://github.com/Paul75> . Sorry if I misunderstood. I
> think your issue is similar to this: #87
> <https://github.com/dm77/barcodescanner/issues/87>. Am I wrong?
>
> If it is the same, then the fix is to use a full screen theme, and any
> other view elements need to be overlaid on top of the camera preview.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dm77/barcodescanner/issues/85#issuecomment-106248295>.
>



-- 
Paul

**Comment by dm77** [comment]
Ok cool, please use a fullscreen theme and lay out any other elements on top of the scanner view and you should be good. See my comment in #67  which has the XML layout and Full screen theme for example.

**Comment by Climbatize** [comment]
the fix worked for me too, thanks @dm77 !
I was losing hope with my client wanting a vertical scanner view XD
