### ISSUE TITLE
Modify Scanner View Colors

### ISSUE THREAD

**Issue by shenoudab** [dm77/barcodescanner#88]
Dears, 

 First Thanks for the great library Dushyanth.

Kindly, how can i modify the colours of the scan borders (green square angels) also the middle red line.
also removing the black bars from both sides in Portrait and Landscape views.

Thanks and Best Regards,
Shenouda Bertel

**Comment by dm77** [comment]
Hi @shenoudab 

No problem. For changing the colors take a look at the default color resources here: https://github.com/dm77/barcodescanner/blob/master/core/src/main/res/values/colors.xml

So all you will have to do is override these resources in your project.

As for the black bars, it only occurs when there are other views in your layout taking up the screen space. We could stretch the camera preview to take up the remaining size but that would mean issues like this #8 and would also mean QR scanning wouldn't work in extreme cases. 

So the solution to that would be to overlay the elements. See the samples if you need further help and also look at the sample XML provided in issue #67
