### ISSUE TITLE
How to know when barcode is detected

### ISSUE THREAD

**Issue by termi123** [dm77/barcodescanner#90]
I want when the barcode is detected,  the border will change color
And I recognized that camera was delayed when decode barcode.  How can i fix that
Can anybody help me

**Comment by johan-schoeman** [comment]
If you add this to your project then the notification sound will play upon a successful scan:

    @Override
    public void handleResult(Result rawResult) {
        try {
            Uri notification = RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION);
            Ringtone r = RingtoneManager.getRingtone(ba.context, notification);
            r.play();
        } catch (Exception e) ....

You need to import:
import android.media.Ringtone;
import android.media.RingtoneManager;
import android.net.Uri;

into your project.
