### ISSUE TITLE
[Bug] An error occurred while connecting to camera: 0

### ISSUE THREAD

**Issue by StErMi** [dm77/barcodescanner#92]
I'm using the latest version `me.dm7.barcodescanner:zxing:1.7.2` from Gradle.
I've setup up a sample app following the code of the SimpleScannerActivity with all the correct permissions.

When I open the SimpleScannerActivity I get a blackscreen and this error on the Android Log:

`W/CameraBase﹕ An error occurred while connecting to camera: 0`

How can I fix this issue? Thanks.

**Comment by merijnbrs** [comment]
Im facing the exact same thing. but perhaps its a little different. If i open the fragment where the barcodescanner is in, it works. if i open a child fragment and go back, it still works. but if i go to another fragment and back (so in an navigation drawer) then i get the same error.
Its driving me really nuts!

**Comment by Cross22** [comment]
When I saw this issue it was because I had added <uses-permission android:name="android.permission.CAMERA" /> to the Application tag, whereas it should be under the manifest tag. Moving it up a line resolved this.

**Comment by jmuthad** [comment]
this can also be caused by calling start camera more then once before calling stop.

**Comment by heitorcolangelo** [comment]
In my case, I was forgetting to call **scannerView.stopCamera()** and **scannerView = null** in **onDestroy method.**

**Comment by jmuthad** [comment]
yeah that's another good way to cause it

**Comment by Robbypatel1357** [comment]
Hello my device is Lg Optimus exceed 2 4.4.2.
We already put Camera Permission

**Comment by dm77** [comment]
Closing as this doesn't sound like a bug in the library.

**Comment by sevenbitsriddhi** [comment]
my problem solved when I realized I was calling `startcamera` multiple times! Now, My question is, is there any ways that I can check weather the camera is satrted or not?
