### ISSUE TITLE
ZBarScannerView custom size

### ISSUE THREAD

**Issue by pelletalexandre** [dm77/barcodescanner#95]
Hello

I'm trying to insert the ZBarScannerView into the top of a fragment, with 100% width and 150dp height.

It almost works but the image ratio is not good, the image is "flat"...

So, how can i set a custom size for this view in order to see only the corrsponding part of the image with good ratio.

Thanks
Regards
Alexandre

**Comment by yoavst** [comment]
Yea I'm also use it in Square layout and it doesn't look good

**Comment by dm77** [comment]
Merged in #101. Hopefully should help with what you are looking for.

**Comment by dm77** [comment]
Will release version 1.8.1 in next 24 to 48 hours.
